# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test RapmScores")

model_instance <- RapmScores$new()

test_that("id", {
  # tests for the property `id` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("api_id", {
  # tests for the property `api_id` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`api_id`, "EXPECTED_RESULT")
})

test_that("season", {
  # tests for the property `season` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`season`, "EXPECTED_RESULT")
})

test_that("session", {
  # tests for the property `session` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`session`, "EXPECTED_RESULT")
})

test_that("situation", {
  # tests for the property `situation` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`situation`, "EXPECTED_RESULT")
})

test_that("team", {
  # tests for the property `team` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`team`, "EXPECTED_RESULT")
})

test_that("pos", {
  # tests for the property `pos` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`pos`, "EXPECTED_RESULT")
})

test_that("pos2", {
  # tests for the property `pos2` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`pos2`, "EXPECTED_RESULT")
})

test_that("toi_minutes", {
  # tests for the property `toi_minutes` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`toi_minutes`, "EXPECTED_RESULT")
})

test_that("rapm_off", {
  # tests for the property `rapm_off` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`rapm_off`, "EXPECTED_RESULT")
})

test_that("rapm_def", {
  # tests for the property `rapm_def` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`rapm_def`, "EXPECTED_RESULT")
})

test_that("off_coeff_corsi", {
  # tests for the property `off_coeff_corsi` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`off_coeff_corsi`, "EXPECTED_RESULT")
})

test_that("off_coeff_goals", {
  # tests for the property `off_coeff_goals` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`off_coeff_goals`, "EXPECTED_RESULT")
})

test_that("def_coeff_corsi", {
  # tests for the property `def_coeff_corsi` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`def_coeff_corsi`, "EXPECTED_RESULT")
})

test_that("def_coeff_goals", {
  # tests for the property `def_coeff_goals` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`def_coeff_goals`, "EXPECTED_RESULT")
})

test_that("metric_for_context_xg", {
  # tests for the property `metric_for_context_xg` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`metric_for_context_xg`, "EXPECTED_RESULT")
})

test_that("metric_against_context_xg", {
  # tests for the property `metric_against_context_xg` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`metric_against_context_xg`, "EXPECTED_RESULT")
})

test_that("metric_diff_context_xg", {
  # tests for the property `metric_diff_context_xg` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`metric_diff_context_xg`, "EXPECTED_RESULT")
})

test_that("metric_for_corsi", {
  # tests for the property `metric_for_corsi` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`metric_for_corsi`, "EXPECTED_RESULT")
})

test_that("metric_against_corsi", {
  # tests for the property `metric_against_corsi` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`metric_against_corsi`, "EXPECTED_RESULT")
})

test_that("metric_diff_corsi", {
  # tests for the property `metric_diff_corsi` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`metric_diff_corsi`, "EXPECTED_RESULT")
})

test_that("metric_for_goals", {
  # tests for the property `metric_for_goals` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`metric_for_goals`, "EXPECTED_RESULT")
})

test_that("metric_against_goals", {
  # tests for the property `metric_against_goals` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`metric_against_goals`, "EXPECTED_RESULT")
})

test_that("metric_diff_goals", {
  # tests for the property `metric_diff_goals` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`metric_diff_goals`, "EXPECTED_RESULT")
})

test_that("on_ice_for_60_context_xg", {
  # tests for the property `on_ice_for_60_context_xg` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`on_ice_for_60_context_xg`, "EXPECTED_RESULT")
})

test_that("on_ice_against_60_context_xg", {
  # tests for the property `on_ice_against_60_context_xg` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`on_ice_against_60_context_xg`, "EXPECTED_RESULT")
})

test_that("on_ice_diff_60_context_xg", {
  # tests for the property `on_ice_diff_60_context_xg` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`on_ice_diff_60_context_xg`, "EXPECTED_RESULT")
})

test_that("on_ice_for_60_corsi", {
  # tests for the property `on_ice_for_60_corsi` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`on_ice_for_60_corsi`, "EXPECTED_RESULT")
})

test_that("on_ice_against_60_corsi", {
  # tests for the property `on_ice_against_60_corsi` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`on_ice_against_60_corsi`, "EXPECTED_RESULT")
})

test_that("on_ice_diff_60_corsi", {
  # tests for the property `on_ice_diff_60_corsi` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`on_ice_diff_60_corsi`, "EXPECTED_RESULT")
})

test_that("on_ice_for_60_goals", {
  # tests for the property `on_ice_for_60_goals` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`on_ice_for_60_goals`, "EXPECTED_RESULT")
})

test_that("on_ice_against_60_goals", {
  # tests for the property `on_ice_against_60_goals` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`on_ice_against_60_goals`, "EXPECTED_RESULT")
})

test_that("on_ice_diff_60_goals", {
  # tests for the property `on_ice_diff_60_goals` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`on_ice_diff_60_goals`, "EXPECTED_RESULT")
})

test_that("total_rapm_context_xg", {
  # tests for the property `total_rapm_context_xg` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`total_rapm_context_xg`, "EXPECTED_RESULT")
})

test_that("total_rapm_corsi", {
  # tests for the property `total_rapm_corsi` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`total_rapm_corsi`, "EXPECTED_RESULT")
})

test_that("total_rapm_goals", {
  # tests for the property `total_rapm_goals` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`total_rapm_goals`, "EXPECTED_RESULT")
})

test_that("off_coeff_context_xg_z", {
  # tests for the property `off_coeff_context_xg_z` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`off_coeff_context_xg_z`, "EXPECTED_RESULT")
})

test_that("off_coeff_corsi_z", {
  # tests for the property `off_coeff_corsi_z` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`off_coeff_corsi_z`, "EXPECTED_RESULT")
})

test_that("off_coeff_goals_z", {
  # tests for the property `off_coeff_goals_z` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`off_coeff_goals_z`, "EXPECTED_RESULT")
})

test_that("def_coeff_context_xg_z", {
  # tests for the property `def_coeff_context_xg_z` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`def_coeff_context_xg_z`, "EXPECTED_RESULT")
})

test_that("def_coeff_corsi_z", {
  # tests for the property `def_coeff_corsi_z` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`def_coeff_corsi_z`, "EXPECTED_RESULT")
})

test_that("def_coeff_goals_z", {
  # tests for the property `def_coeff_goals_z` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`def_coeff_goals_z`, "EXPECTED_RESULT")
})

test_that("metric_for_context_xg_z", {
  # tests for the property `metric_for_context_xg_z` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`metric_for_context_xg_z`, "EXPECTED_RESULT")
})

test_that("metric_against_context_xg_z", {
  # tests for the property `metric_against_context_xg_z` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`metric_against_context_xg_z`, "EXPECTED_RESULT")
})

test_that("metric_diff_context_xg_z", {
  # tests for the property `metric_diff_context_xg_z` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`metric_diff_context_xg_z`, "EXPECTED_RESULT")
})

test_that("metric_for_corsi_z", {
  # tests for the property `metric_for_corsi_z` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`metric_for_corsi_z`, "EXPECTED_RESULT")
})

test_that("metric_against_corsi_z", {
  # tests for the property `metric_against_corsi_z` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`metric_against_corsi_z`, "EXPECTED_RESULT")
})

test_that("metric_diff_corsi_z", {
  # tests for the property `metric_diff_corsi_z` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`metric_diff_corsi_z`, "EXPECTED_RESULT")
})

test_that("metric_for_goals_z", {
  # tests for the property `metric_for_goals_z` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`metric_for_goals_z`, "EXPECTED_RESULT")
})

test_that("metric_against_goals_z", {
  # tests for the property `metric_against_goals_z` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`metric_against_goals_z`, "EXPECTED_RESULT")
})

test_that("metric_diff_goals_z", {
  # tests for the property `metric_diff_goals_z` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`metric_diff_goals_z`, "EXPECTED_RESULT")
})

test_that("on_ice_for_60_context_xg_z", {
  # tests for the property `on_ice_for_60_context_xg_z` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`on_ice_for_60_context_xg_z`, "EXPECTED_RESULT")
})

test_that("on_ice_against_60_context_xg_z", {
  # tests for the property `on_ice_against_60_context_xg_z` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`on_ice_against_60_context_xg_z`, "EXPECTED_RESULT")
})

test_that("on_ice_diff_60_context_xg_z", {
  # tests for the property `on_ice_diff_60_context_xg_z` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`on_ice_diff_60_context_xg_z`, "EXPECTED_RESULT")
})

test_that("on_ice_for_60_corsi_z", {
  # tests for the property `on_ice_for_60_corsi_z` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`on_ice_for_60_corsi_z`, "EXPECTED_RESULT")
})

test_that("on_ice_against_60_corsi_z", {
  # tests for the property `on_ice_against_60_corsi_z` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`on_ice_against_60_corsi_z`, "EXPECTED_RESULT")
})

test_that("on_ice_diff_60_corsi_z", {
  # tests for the property `on_ice_diff_60_corsi_z` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`on_ice_diff_60_corsi_z`, "EXPECTED_RESULT")
})

test_that("on_ice_for_60_goals_z", {
  # tests for the property `on_ice_for_60_goals_z` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`on_ice_for_60_goals_z`, "EXPECTED_RESULT")
})

test_that("on_ice_against_60_goals_z", {
  # tests for the property `on_ice_against_60_goals_z` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`on_ice_against_60_goals_z`, "EXPECTED_RESULT")
})

test_that("on_ice_diff_60_goals_z", {
  # tests for the property `on_ice_diff_60_goals_z` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`on_ice_diff_60_goals_z`, "EXPECTED_RESULT")
})

test_that("total_rapm_context_xg_z", {
  # tests for the property `total_rapm_context_xg_z` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`total_rapm_context_xg_z`, "EXPECTED_RESULT")
})

test_that("total_rapm_corsi_z", {
  # tests for the property `total_rapm_corsi_z` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`total_rapm_corsi_z`, "EXPECTED_RESULT")
})

test_that("total_rapm_goals_z", {
  # tests for the property `total_rapm_goals_z` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`total_rapm_goals_z`, "EXPECTED_RESULT")
})
