# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test StandingsApi")

api_instance <- StandingsApi$new()

test_that("ReadStandings", {
  # tests for ReadStandings
  # base path: https://api.chickenstats.com
  # Read Standings
  # @param season array[integer]  (optional)
  # @param team array[character]  (optional)
  # @return [StandingsResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
