# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test LinesApi")

api_instance <- LinesApi$new()

test_that("ReadGameLines", {
  # tests for ReadGameLines
  # base path: https://api.chickenstats.com
  # Read Game Lines
  # @param limit integer  (optional)
  # @param offset integer  (optional)
  # @param with_total character Include the exact total row count. Set false on broad queries: the count scans every matching row, which on a season-wide filter costs far more than the page itself. `total` is then -1 and `has_next` still works. (optional)
  # @param season array[integer]  (optional)
  # @param sessions array[character]  (optional)
  # @param game_id array[integer]  (optional)
  # @param team array[character]  (optional)
  # @param opp_team array[character]  (optional)
  # @param strength_state array[character]  (optional)
  # @param score_state character  (optional)
  # @param level character  (optional)
  # @param linemates character  (optional)
  # @param opposition character  (optional)
  # @param include array[character]  (optional)
  # @return [LinesGameResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ReadLinesGameIds", {
  # tests for ReadLinesGameIds
  # base path: https://api.chickenstats.com
  # Read Lines Game Ids
  # @param limit integer  (optional)
  # @param offset integer  (optional)
  # @param with_total character Include the exact total row count. Set false on broad queries: the count scans every matching row, which on a season-wide filter costs far more than the page itself. `total` is then -1 and `has_next` still works. (optional)
  # @param season array[integer]  (optional)
  # @param sessions array[character]  (optional)
  # @return [array[integer]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ReadSeasonLines", {
  # tests for ReadSeasonLines
  # base path: https://api.chickenstats.com
  # Read Season Lines
  # @param limit integer  (optional)
  # @param offset integer  (optional)
  # @param with_total character Include the exact total row count. Set false on broad queries: the count scans every matching row, which on a season-wide filter costs far more than the page itself. `total` is then -1 and `has_next` still works. (optional)
  # @param season array[integer]  (optional)
  # @param sessions array[character]  (optional)
  # @param team array[character]  (optional)
  # @param opp_team array[character]  (optional)
  # @param strength_state array[character]  (optional)
  # @param score_state character  (optional)
  # @param linemates character  (optional)
  # @param opposition character  (optional)
  # @return [LinesSeasonResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
