# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test InferenceApi")

api_instance <- InferenceApi$new()

test_that("ReadPredGoal", {
  # tests for ReadPredGoal
  # base path: https://api.chickenstats.com
  # Read Pred Goal
  # Pre-computed pred_goal values from pbpcs for shot/miss/goal events.
  # @param game_id array[integer]  (optional)
  # @param season array[integer]  (optional)
  # @param sessions array[character]  (optional)
  # @param limit integer  (optional)
  # @param offset integer  (optional)
  # @return [PredGoalResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
