# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test PlayerPublic")

model_instance <- PlayerPublic$new()

test_that("api_id", {
  # tests for the property `api_id` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`api_id`, "EXPECTED_RESULT")
})

test_that("eh_id", {
  # tests for the property `eh_id` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`eh_id`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("position", {
  # tests for the property `position` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`position`, "EXPECTED_RESULT")
})

test_that("shoots", {
  # tests for the property `shoots` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`shoots`, "EXPECTED_RESULT")
})

test_that("catches", {
  # tests for the property `catches` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`catches`, "EXPECTED_RESULT")
})

test_that("birth_date", {
  # tests for the property `birth_date` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`birth_date`, "EXPECTED_RESULT")
})

test_that("birth_city", {
  # tests for the property `birth_city` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`birth_city`, "EXPECTED_RESULT")
})

test_that("birth_state_province", {
  # tests for the property `birth_state_province` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`birth_state_province`, "EXPECTED_RESULT")
})

test_that("birth_country", {
  # tests for the property `birth_country` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`birth_country`, "EXPECTED_RESULT")
})

test_that("nationality", {
  # tests for the property `nationality` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`nationality`, "EXPECTED_RESULT")
})

test_that("height", {
  # tests for the property `height` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`height`, "EXPECTED_RESULT")
})

test_that("weight", {
  # tests for the property `weight` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`weight`, "EXPECTED_RESULT")
})
