# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test PredGoalRow")

model_instance <- PredGoalRow$new()

test_that("game_id", {
  # tests for the property `game_id` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`game_id`, "EXPECTED_RESULT")
})

test_that("event_idx", {
  # tests for the property `event_idx` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`event_idx`, "EXPECTED_RESULT")
})

test_that("season", {
  # tests for the property `season` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`season`, "EXPECTED_RESULT")
})

test_that("session", {
  # tests for the property `session` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`session`, "EXPECTED_RESULT")
})

test_that("base_xg", {
  # tests for the property `base_xg` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`base_xg`, "EXPECTED_RESULT")
})

test_that("pred_goal", {
  # tests for the property `pred_goal` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`pred_goal`, "EXPECTED_RESULT")
})
