# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test TeamStatsApi")

api_instance <- TeamStatsApi$new()

test_that("ReadGameTeamStats", {
  # tests for ReadGameTeamStats
  # base path: https://api.chickenstats.com
  # Read Game Team Stats
  # @param season array[integer]  (optional)
  # @param sessions array[character]  (optional)
  # @param game_id array[integer]  (optional)
  # @param team array[character]  (optional)
  # @param opp_team array[character]  (optional)
  # @param strength_state array[character]  (optional)
  # @param score_state character  (optional)
  # @param level character  (optional)
  # @param limit integer  (optional)
  # @param offset integer  (optional)
  # @return [TeamStatsGameResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ReadSeasonTeamStats", {
  # tests for ReadSeasonTeamStats
  # base path: https://api.chickenstats.com
  # Read Season Team Stats
  # @param season array[integer]  (optional)
  # @param sessions array[character]  (optional)
  # @param team array[character]  (optional)
  # @param opp_team array[character]  (optional)
  # @param strength_state array[character]  (optional)
  # @param score_state character  (optional)
  # @param limit integer  (optional)
  # @param offset integer  (optional)
  # @return [TeamStatsSeasonResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ReadTeamStatsGameIds", {
  # tests for ReadTeamStatsGameIds
  # base path: https://api.chickenstats.com
  # Read Team Stats Game Ids
  # @param season array[integer]  (optional)
  # @param sessions array[character]  (optional)
  # @return [array[integer]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ReadTeamStatsIds", {
  # tests for ReadTeamStatsIds
  # base path: https://api.chickenstats.com
  # Read Team Stats Ids
  # @param season array[integer]  (optional)
  # @param sessions array[character]  (optional)
  # @return [array[character]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
