# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test TeamsApi")

api_instance <- TeamsApi$new()

test_that("ReadTeams", {
  # tests for ReadTeams
  # base path: https://api.chickenstats.com
  # Read Teams
  # @return [TeamResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
