# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test GamesApi")

api_instance <- GamesApi$new()

test_that("ReadGame", {
  # tests for ReadGame
  # base path: https://api.chickenstats.com
  # Read Game
  # @param game_id integer 
  # @return [GamePublic]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ReadGames", {
  # tests for ReadGames
  # base path: https://api.chickenstats.com
  # Read Games
  # @param limit integer  (optional)
  # @param offset integer  (optional)
  # @param with_total character Include the exact total row count. Set false on broad queries: the count scans every matching row, which on a season-wide filter costs far more than the page itself. `total` is then -1 and `has_next` still works. (optional)
  # @param season array[integer]  (optional)
  # @param sessions array[character]  (optional)
  # @param team array[character]  (optional)
  # @return [GameResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
