# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test LiveGamesPublic")

model_instance <- LiveGamesPublic$new()

test_that("game_id", {
  # tests for the property `game_id` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`game_id`, "EXPECTED_RESULT")
})

test_that("game_date", {
  # tests for the property `game_date` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`game_date`, "EXPECTED_RESULT")
})

test_that("home_team", {
  # tests for the property `home_team` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`home_team`, "EXPECTED_RESULT")
})

test_that("away_team", {
  # tests for the property `away_team` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`away_team`, "EXPECTED_RESULT")
})

test_that("game_state", {
  # tests for the property `game_state` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`game_state`, "EXPECTED_RESULT")
})

test_that("period", {
  # tests for the property `period` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`period`, "EXPECTED_RESULT")
})

test_that("time_remaining", {
  # tests for the property `time_remaining` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`time_remaining`, "EXPECTED_RESULT")
})

test_that("home_score", {
  # tests for the property `home_score` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`home_score`, "EXPECTED_RESULT")
})

test_that("away_score", {
  # tests for the property `away_score` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`away_score`, "EXPECTED_RESULT")
})

test_that("last_updated", {
  # tests for the property `last_updated` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`last_updated`, "EXPECTED_RESULT")
})
