# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test LoginApi")

api_instance <- LoginApi$new()

test_that("LoginAuth0Token", {
  # tests for LoginAuth0Token
  # base path: https://api.chickenstats.com
  # Login Auth0 Token
  # Exchange email + password for an Auth0 access token (for use with API data endpoints).
  # @param username character 
  # @param password character 
  # @param grant_type character  (optional)
  # @param scope character  (optional)
  # @param client_id character  (optional)
  # @param client_secret character  (optional)
  # @return [Token]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("LoginCallback", {
  # tests for LoginCallback
  # base path: https://api.chickenstats.com
  # Login Callback
  # Exchange an Auth0 authorization code (Universal Login) for a local HS256 session token.
  # @param code character 
  # @return [Token]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("RecoverPassword", {
  # tests for RecoverPassword
  # base path: https://api.chickenstats.com
  # Recover Password
  # Always returns 200 to prevent email enumeration.
  # @param email character 
  # @return [Message]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("RecoverPasswordHtmlContent", {
  # tests for RecoverPasswordHtmlContent
  # base path: https://api.chickenstats.com
  # Recover Password Html Content
  # HTML Content for Password Recovery.
  # @param email character 
  # @return [character]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ResetPassword", {
  # tests for ResetPassword
  # base path: https://api.chickenstats.com
  # Reset Password
  # Reset password using the token from the recovery email.
  # @param new_password NewPassword 
  # @return [Message]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("TestToken", {
  # tests for TestToken
  # base path: https://api.chickenstats.com
  # Test Token
  # Test access token.
  # @return [UserPublic]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
