# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test StatsSeason")

model_instance <- StatsSeason$new()

test_that("season", {
  # tests for the property `season` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`season`, "EXPECTED_RESULT")
})

test_that("session", {
  # tests for the property `session` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`session`, "EXPECTED_RESULT")
})

test_that("game_id", {
  # tests for the property `game_id` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`game_id`, "EXPECTED_RESULT")
})

test_that("game_date", {
  # tests for the property `game_date` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`game_date`, "EXPECTED_RESULT")
})

test_that("player", {
  # tests for the property `player` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`player`, "EXPECTED_RESULT")
})

test_that("eh_id", {
  # tests for the property `eh_id` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`eh_id`, "EXPECTED_RESULT")
})

test_that("api_id", {
  # tests for the property `api_id` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`api_id`, "EXPECTED_RESULT")
})

test_that("position", {
  # tests for the property `position` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`position`, "EXPECTED_RESULT")
})

test_that("team", {
  # tests for the property `team` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`team`, "EXPECTED_RESULT")
})

test_that("opp_team", {
  # tests for the property `opp_team` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`opp_team`, "EXPECTED_RESULT")
})

test_that("strength_state", {
  # tests for the property `strength_state` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`strength_state`, "EXPECTED_RESULT")
})

test_that("period", {
  # tests for the property `period` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`period`, "EXPECTED_RESULT")
})

test_that("score_state", {
  # tests for the property `score_state` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`score_state`, "EXPECTED_RESULT")
})

test_that("forwards", {
  # tests for the property `forwards` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`forwards`, "EXPECTED_RESULT")
})

test_that("forwards_eh_id", {
  # tests for the property `forwards_eh_id` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`forwards_eh_id`, "EXPECTED_RESULT")
})

test_that("forwards_api_id", {
  # tests for the property `forwards_api_id` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`forwards_api_id`, "EXPECTED_RESULT")
})

test_that("defense", {
  # tests for the property `defense` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`defense`, "EXPECTED_RESULT")
})

test_that("defense_eh_id", {
  # tests for the property `defense_eh_id` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`defense_eh_id`, "EXPECTED_RESULT")
})

test_that("defense_api_id", {
  # tests for the property `defense_api_id` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`defense_api_id`, "EXPECTED_RESULT")
})

test_that("own_goalie", {
  # tests for the property `own_goalie` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`own_goalie`, "EXPECTED_RESULT")
})

test_that("own_goalie_eh_id", {
  # tests for the property `own_goalie_eh_id` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`own_goalie_eh_id`, "EXPECTED_RESULT")
})

test_that("own_goalie_api_id", {
  # tests for the property `own_goalie_api_id` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`own_goalie_api_id`, "EXPECTED_RESULT")
})

test_that("opp_forwards", {
  # tests for the property `opp_forwards` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`opp_forwards`, "EXPECTED_RESULT")
})

test_that("opp_forwards_eh_id", {
  # tests for the property `opp_forwards_eh_id` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`opp_forwards_eh_id`, "EXPECTED_RESULT")
})

test_that("opp_forwards_api_id", {
  # tests for the property `opp_forwards_api_id` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`opp_forwards_api_id`, "EXPECTED_RESULT")
})

test_that("opp_defense", {
  # tests for the property `opp_defense` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`opp_defense`, "EXPECTED_RESULT")
})

test_that("opp_defense_eh_id", {
  # tests for the property `opp_defense_eh_id` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`opp_defense_eh_id`, "EXPECTED_RESULT")
})

test_that("opp_defense_api_id", {
  # tests for the property `opp_defense_api_id` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`opp_defense_api_id`, "EXPECTED_RESULT")
})

test_that("opp_goalie", {
  # tests for the property `opp_goalie` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`opp_goalie`, "EXPECTED_RESULT")
})

test_that("opp_goalie_eh_id", {
  # tests for the property `opp_goalie_eh_id` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`opp_goalie_eh_id`, "EXPECTED_RESULT")
})

test_that("opp_goalie_api_id", {
  # tests for the property `opp_goalie_api_id` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`opp_goalie_api_id`, "EXPECTED_RESULT")
})

test_that("toi", {
  # tests for the property `toi` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`toi`, "EXPECTED_RESULT")
})

test_that("g", {
  # tests for the property `g` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`g`, "EXPECTED_RESULT")
})

test_that("g_adj", {
  # tests for the property `g_adj` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`g_adj`, "EXPECTED_RESULT")
})

test_that("ihdg", {
  # tests for the property `ihdg` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`ihdg`, "EXPECTED_RESULT")
})

test_that("a1", {
  # tests for the property `a1` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`a1`, "EXPECTED_RESULT")
})

test_that("a2", {
  # tests for the property `a2` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`a2`, "EXPECTED_RESULT")
})

test_that("base_ixg", {
  # tests for the property `base_ixg` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`base_ixg`, "EXPECTED_RESULT")
})

test_that("base_ixg_adj", {
  # tests for the property `base_ixg_adj` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`base_ixg_adj`, "EXPECTED_RESULT")
})

test_that("ixg", {
  # tests for the property `ixg` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`ixg`, "EXPECTED_RESULT")
})

test_that("ixg_adj", {
  # tests for the property `ixg_adj` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`ixg_adj`, "EXPECTED_RESULT")
})

test_that("context_ixg", {
  # tests for the property `context_ixg` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`context_ixg`, "EXPECTED_RESULT")
})

test_that("context_ixg_adj", {
  # tests for the property `context_ixg_adj` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`context_ixg_adj`, "EXPECTED_RESULT")
})

test_that("isf", {
  # tests for the property `isf` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`isf`, "EXPECTED_RESULT")
})

test_that("isf_adj", {
  # tests for the property `isf_adj` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`isf_adj`, "EXPECTED_RESULT")
})

test_that("ihdsf", {
  # tests for the property `ihdsf` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`ihdsf`, "EXPECTED_RESULT")
})

test_that("imsf", {
  # tests for the property `imsf` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`imsf`, "EXPECTED_RESULT")
})

test_that("imsf_adj", {
  # tests for the property `imsf_adj` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`imsf_adj`, "EXPECTED_RESULT")
})

test_that("ihdm", {
  # tests for the property `ihdm` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`ihdm`, "EXPECTED_RESULT")
})

test_that("iff", {
  # tests for the property `iff` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`iff`, "EXPECTED_RESULT")
})

test_that("iff_adj", {
  # tests for the property `iff_adj` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`iff_adj`, "EXPECTED_RESULT")
})

test_that("ihdf", {
  # tests for the property `ihdf` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`ihdf`, "EXPECTED_RESULT")
})

test_that("isb", {
  # tests for the property `isb` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`isb`, "EXPECTED_RESULT")
})

test_that("isb_adj", {
  # tests for the property `isb_adj` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`isb_adj`, "EXPECTED_RESULT")
})

test_that("icf", {
  # tests for the property `icf` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`icf`, "EXPECTED_RESULT")
})

test_that("icf_adj", {
  # tests for the property `icf_adj` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`icf_adj`, "EXPECTED_RESULT")
})

test_that("ibs", {
  # tests for the property `ibs` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`ibs`, "EXPECTED_RESULT")
})

test_that("ibs_adj", {
  # tests for the property `ibs_adj` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`ibs_adj`, "EXPECTED_RESULT")
})

test_that("igive", {
  # tests for the property `igive` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`igive`, "EXPECTED_RESULT")
})

test_that("itake", {
  # tests for the property `itake` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`itake`, "EXPECTED_RESULT")
})

test_that("ihf", {
  # tests for the property `ihf` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`ihf`, "EXPECTED_RESULT")
})

test_that("iht", {
  # tests for the property `iht` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`iht`, "EXPECTED_RESULT")
})

test_that("ifow", {
  # tests for the property `ifow` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`ifow`, "EXPECTED_RESULT")
})

test_that("ifol", {
  # tests for the property `ifol` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`ifol`, "EXPECTED_RESULT")
})

test_that("iozfw", {
  # tests for the property `iozfw` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`iozfw`, "EXPECTED_RESULT")
})

test_that("iozfl", {
  # tests for the property `iozfl` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`iozfl`, "EXPECTED_RESULT")
})

test_that("inzfw", {
  # tests for the property `inzfw` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`inzfw`, "EXPECTED_RESULT")
})

test_that("inzfl", {
  # tests for the property `inzfl` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`inzfl`, "EXPECTED_RESULT")
})

test_that("idzfw", {
  # tests for the property `idzfw` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`idzfw`, "EXPECTED_RESULT")
})

test_that("idzfl", {
  # tests for the property `idzfl` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`idzfl`, "EXPECTED_RESULT")
})

test_that("a1_xg", {
  # tests for the property `a1_xg` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`a1_xg`, "EXPECTED_RESULT")
})

test_that("a2_xg", {
  # tests for the property `a2_xg` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`a2_xg`, "EXPECTED_RESULT")
})

test_that("ipent0", {
  # tests for the property `ipent0` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`ipent0`, "EXPECTED_RESULT")
})

test_that("ipent2", {
  # tests for the property `ipent2` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`ipent2`, "EXPECTED_RESULT")
})

test_that("ipent4", {
  # tests for the property `ipent4` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`ipent4`, "EXPECTED_RESULT")
})

test_that("ipent5", {
  # tests for the property `ipent5` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`ipent5`, "EXPECTED_RESULT")
})

test_that("ipent10", {
  # tests for the property `ipent10` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`ipent10`, "EXPECTED_RESULT")
})

test_that("ipend0", {
  # tests for the property `ipend0` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`ipend0`, "EXPECTED_RESULT")
})

test_that("ipend2", {
  # tests for the property `ipend2` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`ipend2`, "EXPECTED_RESULT")
})

test_that("ipend4", {
  # tests for the property `ipend4` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`ipend4`, "EXPECTED_RESULT")
})

test_that("ipend5", {
  # tests for the property `ipend5` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`ipend5`, "EXPECTED_RESULT")
})

test_that("ipend10", {
  # tests for the property `ipend10` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`ipend10`, "EXPECTED_RESULT")
})

test_that("gf", {
  # tests for the property `gf` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`gf`, "EXPECTED_RESULT")
})

test_that("ga", {
  # tests for the property `ga` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`ga`, "EXPECTED_RESULT")
})

test_that("gf_adj", {
  # tests for the property `gf_adj` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`gf_adj`, "EXPECTED_RESULT")
})

test_that("ga_adj", {
  # tests for the property `ga_adj` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`ga_adj`, "EXPECTED_RESULT")
})

test_that("hdgf", {
  # tests for the property `hdgf` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`hdgf`, "EXPECTED_RESULT")
})

test_that("hdga", {
  # tests for the property `hdga` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`hdga`, "EXPECTED_RESULT")
})

test_that("base_xgf", {
  # tests for the property `base_xgf` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`base_xgf`, "EXPECTED_RESULT")
})

test_that("base_xga", {
  # tests for the property `base_xga` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`base_xga`, "EXPECTED_RESULT")
})

test_that("base_xgf_adj", {
  # tests for the property `base_xgf_adj` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`base_xgf_adj`, "EXPECTED_RESULT")
})

test_that("base_xga_adj", {
  # tests for the property `base_xga_adj` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`base_xga_adj`, "EXPECTED_RESULT")
})

test_that("context_xgf", {
  # tests for the property `context_xgf` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`context_xgf`, "EXPECTED_RESULT")
})

test_that("context_xga", {
  # tests for the property `context_xga` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`context_xga`, "EXPECTED_RESULT")
})

test_that("context_xgf_adj", {
  # tests for the property `context_xgf_adj` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`context_xgf_adj`, "EXPECTED_RESULT")
})

test_that("context_xga_adj", {
  # tests for the property `context_xga_adj` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`context_xga_adj`, "EXPECTED_RESULT")
})

test_that("xgf", {
  # tests for the property `xgf` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`xgf`, "EXPECTED_RESULT")
})

test_that("xga", {
  # tests for the property `xga` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`xga`, "EXPECTED_RESULT")
})

test_that("xgf_adj", {
  # tests for the property `xgf_adj` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`xgf_adj`, "EXPECTED_RESULT")
})

test_that("xga_adj", {
  # tests for the property `xga_adj` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`xga_adj`, "EXPECTED_RESULT")
})

test_that("sf", {
  # tests for the property `sf` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`sf`, "EXPECTED_RESULT")
})

test_that("sa", {
  # tests for the property `sa` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`sa`, "EXPECTED_RESULT")
})

test_that("sf_adj", {
  # tests for the property `sf_adj` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`sf_adj`, "EXPECTED_RESULT")
})

test_that("sa_adj", {
  # tests for the property `sa_adj` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`sa_adj`, "EXPECTED_RESULT")
})

test_that("hdsf", {
  # tests for the property `hdsf` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`hdsf`, "EXPECTED_RESULT")
})

test_that("hdsa", {
  # tests for the property `hdsa` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`hdsa`, "EXPECTED_RESULT")
})

test_that("ff", {
  # tests for the property `ff` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`ff`, "EXPECTED_RESULT")
})

test_that("fa", {
  # tests for the property `fa` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`fa`, "EXPECTED_RESULT")
})

test_that("ff_adj", {
  # tests for the property `ff_adj` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`ff_adj`, "EXPECTED_RESULT")
})

test_that("fa_adj", {
  # tests for the property `fa_adj` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`fa_adj`, "EXPECTED_RESULT")
})

test_that("hdff", {
  # tests for the property `hdff` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`hdff`, "EXPECTED_RESULT")
})

test_that("hdfa", {
  # tests for the property `hdfa` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`hdfa`, "EXPECTED_RESULT")
})

test_that("cf", {
  # tests for the property `cf` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`cf`, "EXPECTED_RESULT")
})

test_that("ca", {
  # tests for the property `ca` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`ca`, "EXPECTED_RESULT")
})

test_that("cf_adj", {
  # tests for the property `cf_adj` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`cf_adj`, "EXPECTED_RESULT")
})

test_that("ca_adj", {
  # tests for the property `ca_adj` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`ca_adj`, "EXPECTED_RESULT")
})

test_that("bsf", {
  # tests for the property `bsf` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`bsf`, "EXPECTED_RESULT")
})

test_that("bsa", {
  # tests for the property `bsa` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`bsa`, "EXPECTED_RESULT")
})

test_that("bsf_adj", {
  # tests for the property `bsf_adj` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`bsf_adj`, "EXPECTED_RESULT")
})

test_that("bsa_adj", {
  # tests for the property `bsa_adj` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`bsa_adj`, "EXPECTED_RESULT")
})

test_that("msf", {
  # tests for the property `msf` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`msf`, "EXPECTED_RESULT")
})

test_that("msa", {
  # tests for the property `msa` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`msa`, "EXPECTED_RESULT")
})

test_that("msf_adj", {
  # tests for the property `msf_adj` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`msf_adj`, "EXPECTED_RESULT")
})

test_that("msa_adj", {
  # tests for the property `msa_adj` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`msa_adj`, "EXPECTED_RESULT")
})

test_that("hdmsf", {
  # tests for the property `hdmsf` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`hdmsf`, "EXPECTED_RESULT")
})

test_that("hdmsa", {
  # tests for the property `hdmsa` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`hdmsa`, "EXPECTED_RESULT")
})

test_that("teammate_block", {
  # tests for the property `teammate_block` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`teammate_block`, "EXPECTED_RESULT")
})

test_that("teammate_block_adj", {
  # tests for the property `teammate_block_adj` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`teammate_block_adj`, "EXPECTED_RESULT")
})

test_that("hf", {
  # tests for the property `hf` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`hf`, "EXPECTED_RESULT")
})

test_that("ht", {
  # tests for the property `ht` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`ht`, "EXPECTED_RESULT")
})

test_that("ozf", {
  # tests for the property `ozf` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`ozf`, "EXPECTED_RESULT")
})

test_that("nzf", {
  # tests for the property `nzf` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`nzf`, "EXPECTED_RESULT")
})

test_that("dzf", {
  # tests for the property `dzf` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`dzf`, "EXPECTED_RESULT")
})

test_that("fow", {
  # tests for the property `fow` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`fow`, "EXPECTED_RESULT")
})

test_that("fol", {
  # tests for the property `fol` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`fol`, "EXPECTED_RESULT")
})

test_that("ozfw", {
  # tests for the property `ozfw` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`ozfw`, "EXPECTED_RESULT")
})

test_that("ozfl", {
  # tests for the property `ozfl` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`ozfl`, "EXPECTED_RESULT")
})

test_that("nzfw", {
  # tests for the property `nzfw` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`nzfw`, "EXPECTED_RESULT")
})

test_that("nzfl", {
  # tests for the property `nzfl` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`nzfl`, "EXPECTED_RESULT")
})

test_that("dzfw", {
  # tests for the property `dzfw` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`dzfw`, "EXPECTED_RESULT")
})

test_that("dzfl", {
  # tests for the property `dzfl` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`dzfl`, "EXPECTED_RESULT")
})

test_that("pent0", {
  # tests for the property `pent0` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`pent0`, "EXPECTED_RESULT")
})

test_that("pent2", {
  # tests for the property `pent2` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`pent2`, "EXPECTED_RESULT")
})

test_that("pent4", {
  # tests for the property `pent4` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`pent4`, "EXPECTED_RESULT")
})

test_that("pent5", {
  # tests for the property `pent5` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`pent5`, "EXPECTED_RESULT")
})

test_that("pent10", {
  # tests for the property `pent10` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`pent10`, "EXPECTED_RESULT")
})

test_that("pend0", {
  # tests for the property `pend0` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`pend0`, "EXPECTED_RESULT")
})

test_that("pend2", {
  # tests for the property `pend2` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`pend2`, "EXPECTED_RESULT")
})

test_that("pend4", {
  # tests for the property `pend4` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`pend4`, "EXPECTED_RESULT")
})

test_that("pend5", {
  # tests for the property `pend5` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`pend5`, "EXPECTED_RESULT")
})

test_that("pend10", {
  # tests for the property `pend10` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`pend10`, "EXPECTED_RESULT")
})

test_that("ozs", {
  # tests for the property `ozs` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`ozs`, "EXPECTED_RESULT")
})

test_that("nzs", {
  # tests for the property `nzs` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`nzs`, "EXPECTED_RESULT")
})

test_that("dzs", {
  # tests for the property `dzs` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`dzs`, "EXPECTED_RESULT")
})

test_that("otf", {
  # tests for the property `otf` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`otf`, "EXPECTED_RESULT")
})
