# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test GamePublic")

model_instance <- GamePublic$new()

test_that("game_id", {
  # tests for the property `game_id` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`game_id`, "EXPECTED_RESULT")
})

test_that("season", {
  # tests for the property `season` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`season`, "EXPECTED_RESULT")
})

test_that("session", {
  # tests for the property `session` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`session`, "EXPECTED_RESULT")
})

test_that("game_date", {
  # tests for the property `game_date` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`game_date`, "EXPECTED_RESULT")
})

test_that("start_time", {
  # tests for the property `start_time` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`start_time`, "EXPECTED_RESULT")
})

test_that("start_time_utc", {
  # tests for the property `start_time_utc` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`start_time_utc`, "EXPECTED_RESULT")
})

test_that("game_state", {
  # tests for the property `game_state` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`game_state`, "EXPECTED_RESULT")
})

test_that("game_schedule_state", {
  # tests for the property `game_schedule_state` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`game_schedule_state`, "EXPECTED_RESULT")
})

test_that("game_outcome", {
  # tests for the property `game_outcome` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`game_outcome`, "EXPECTED_RESULT")
})

test_that("home_team", {
  # tests for the property `home_team` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`home_team`, "EXPECTED_RESULT")
})

test_that("away_team", {
  # tests for the property `away_team` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`away_team`, "EXPECTED_RESULT")
})

test_that("home_score", {
  # tests for the property `home_score` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`home_score`, "EXPECTED_RESULT")
})

test_that("away_score", {
  # tests for the property `away_score` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`away_score`, "EXPECTED_RESULT")
})

test_that("venue", {
  # tests for the property `venue` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`venue`, "EXPECTED_RESULT")
})

test_that("venue_location", {
  # tests for the property `venue_location` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`venue_location`, "EXPECTED_RESULT")
})

test_that("venue_timezone", {
  # tests for the property `venue_timezone` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`venue_timezone`, "EXPECTED_RESULT")
})

test_that("neutral_site", {
  # tests for the property `neutral_site` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`neutral_site`, "EXPECTED_RESULT")
})
