# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test IdToken")

model_instance <- IdToken$new()

test_that("id_token", {
  # tests for the property `id_token` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`id_token`, "EXPECTED_RESULT")
})
