# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test GamesApi")

api_instance <- GamesApi$new()

test_that("ReadGame", {
  # tests for ReadGame
  # base path: https://api.chickenstats.com
  # Read Game
  # @param game_id integer 
  # @return [GamePublic]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ReadGames", {
  # tests for ReadGames
  # base path: https://api.chickenstats.com
  # Read Games
  # @param season array[integer]  (optional)
  # @param sessions array[character]  (optional)
  # @param team array[character]  (optional)
  # @param limit integer  (optional)
  # @param offset integer  (optional)
  # @return [GameResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
