# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test PlayByPlayApi")

api_instance <- PlayByPlayApi$new()

test_that("ReadPbp", {
  # tests for ReadPbp
  # base path: https://api.chickenstats.com
  # Read Pbp
  # @param limit integer  (optional)
  # @param offset integer  (optional)
  # @param with_total character Include the exact total row count. Set false on broad queries: the count scans every matching row, which on a season-wide filter costs far more than the page itself. `total` is then -1 and `has_next` still works. (optional)
  # @param season array[integer]  (optional)
  # @param sessions array[character]  (optional)
  # @param game_id array[integer]  (optional)
  # @param play_id array[integer]  (optional)
  # @param event array[character]  (optional)
  # @param player_1 array[character]  (optional)
  # @param goalie array[character]  (optional)
  # @param event_team array[character]  (optional)
  # @param opp_team array[character]  (optional)
  # @param strength_state array[character]  (optional)
  # @param include array[character]  (optional)
  # @return [PbpResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ReadPbpGameIds", {
  # tests for ReadPbpGameIds
  # base path: https://api.chickenstats.com
  # Read Pbp Game Ids
  # @param limit integer  (optional)
  # @param offset integer  (optional)
  # @param with_total character Include the exact total row count. Set false on broad queries: the count scans every matching row, which on a season-wide filter costs far more than the page itself. `total` is then -1 and `has_next` still works. (optional)
  # @param season array[integer]  (optional)
  # @param sessions array[character]  (optional)
  # @return [array[integer]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ReadPbpPlayIds", {
  # tests for ReadPbpPlayIds
  # base path: https://api.chickenstats.com
  # Read Pbp Play Ids
  # @param limit integer  (optional)
  # @param offset integer  (optional)
  # @param with_total character Include the exact total row count. Set false on broad queries: the count scans every matching row, which on a season-wide filter costs far more than the page itself. `total` is then -1 and `has_next` still works. (optional)
  # @param season array[integer]  (optional)
  # @param sessions array[character]  (optional)
  # @param game_id array[integer]  (optional)
  # @return [array[integer]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
