# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ShiftsPublic")

model_instance <- ShiftsPublic$new()

test_that("season", {
  # tests for the property `season` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`season`, "EXPECTED_RESULT")
})

test_that("session", {
  # tests for the property `session` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`session`, "EXPECTED_RESULT")
})

test_that("game_id", {
  # tests for the property `game_id` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`game_id`, "EXPECTED_RESULT")
})

test_that("api_id", {
  # tests for the property `api_id` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`api_id`, "EXPECTED_RESULT")
})

test_that("team", {
  # tests for the property `team` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`team`, "EXPECTED_RESULT")
})

test_that("shift_count", {
  # tests for the property `shift_count` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`shift_count`, "EXPECTED_RESULT")
})

test_that("period", {
  # tests for the property `period` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`period`, "EXPECTED_RESULT")
})

test_that("start_time_seconds", {
  # tests for the property `start_time_seconds` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`start_time_seconds`, "EXPECTED_RESULT")
})

test_that("end_time_seconds", {
  # tests for the property `end_time_seconds` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`end_time_seconds`, "EXPECTED_RESULT")
})

test_that("duration_seconds", {
  # tests for the property `duration_seconds` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`duration_seconds`, "EXPECTED_RESULT")
})

test_that("goalie", {
  # tests for the property `goalie` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`goalie`, "EXPECTED_RESULT")
})

test_that("is_home", {
  # tests for the property `is_home` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`is_home`, "EXPECTED_RESULT")
})

test_that("is_away", {
  # tests for the property `is_away` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`is_away`, "EXPECTED_RESULT")
})

test_that("player", {
  # tests for the property `player` (PlayerPublic)

  # uncomment below to test the property
  #expect_equal(model.instance$`player`, "EXPECTED_RESULT")
})

test_that("game", {
  # tests for the property `game` (GamePublic)

  # uncomment below to test the property
  #expect_equal(model.instance$`game`, "EXPECTED_RESULT")
})
