# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test RapmResponse")

model_instance <- RapmResponse$new()

test_that("count", {
  # tests for the property `count` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`count`, "EXPECTED_RESULT")
})

test_that("total", {
  # tests for the property `total` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`total`, "EXPECTED_RESULT")
})

test_that("limit", {
  # tests for the property `limit` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`limit`, "EXPECTED_RESULT")
})

test_that("offset", {
  # tests for the property `offset` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`offset`, "EXPECTED_RESULT")
})

test_that("has_next", {
  # tests for the property `has_next` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`has_next`, "EXPECTED_RESULT")
})

test_that("data", {
  # tests for the property `data` (array[RapmScores])

  # uncomment below to test the property
  #expect_equal(model.instance$`data`, "EXPECTED_RESULT")
})
