# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test UsersApi")

api_instance <- UsersApi$new()

test_that("DeleteUserMe", {
  # tests for DeleteUserMe
  # base path: https://api.chickenstats.com
  # Delete User Me
  # Delete own user and block Auth0 account.
  # @return [Message]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetProgrammaticCredentials", {
  # tests for GetProgrammaticCredentials
  # base path: https://api.chickenstats.com
  # Get Programmatic Credentials
  # Return the CF client ID for programmatic access. The secret is never retrievable —.  rotate credentials if the secret was lost.
  # @return [ProgrammaticCredentials]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ReadUserMe", {
  # tests for ReadUserMe
  # base path: https://api.chickenstats.com
  # Read User Me
  # Get current user.
  # @return [UserPublic]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ResendVerification", {
  # tests for ResendVerification
  # base path: https://api.chickenstats.com
  # Resend Verification
  # Trigger Auth0 to resend the verification email.
  # @return [Message]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("RotateProgrammaticCredentials", {
  # tests for RotateProgrammaticCredentials
  # base path: https://api.chickenstats.com
  # Rotate Programmatic Credentials
  # Delete the existing CF service token and issue a new one. The new secret is.  returned once in the response and optionally emailed. Store it immediately.
  # @return [ProgrammaticCredentials]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("Signup", {
  # tests for Signup
  # base path: https://api.chickenstats.com
  # Signup
  # Public self-registration. Creates a local user, an Auth0 user, and a Ghost member.  If the account exists but is inactive (previously deactivated/pruned), reactivates it with the new credentials rather than rejecting the request.
  # @param user_register UserRegister 
  # @return [UserPublic]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("SyncGhostTier", {
  # tests for SyncGhostTier
  # base path: https://api.chickenstats.com
  # Sync Ghost Tier
  # Refresh tier from Ghost subscription state. No-op for contributor/superuser.
  # @return [Message]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("UpdatePasswordMe", {
  # tests for UpdatePasswordMe
  # base path: https://api.chickenstats.com
  # Update Password Me
  # Update own password in Auth0. Verifies current password against Auth0 before changing.
  # @param update_password UpdatePassword 
  # @return [Message]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("UpdateUserMe", {
  # tests for UpdateUserMe
  # base path: https://api.chickenstats.com
  # Update User Me
  # Update own user.
  # @param user_update_me UserUpdateMe 
  # @return [UserPublic]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
