# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test RostersApi")

api_instance <- RostersApi$new()

test_that("ReadRosterGameIds", {
  # tests for ReadRosterGameIds
  # base path: https://api.chickenstats.com
  # Read Roster Game Ids
  # @param api_id array[integer]  (optional)
  # @param team array[character]  (optional)
  # @return [array[integer]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ReadRosters", {
  # tests for ReadRosters
  # base path: https://api.chickenstats.com
  # Read Rosters
  # @param game_id array[integer]  (optional)
  # @param api_id array[integer]  (optional)
  # @param team array[character]  (optional)
  # @param include array[character]  (optional)
  # @param limit integer  (optional)
  # @param offset integer  (optional)
  # @return [RosterResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
