# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test PbpPublic")

model_instance <- PbpPublic$new()

test_that("id", {
  # tests for the property `id` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("season", {
  # tests for the property `season` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`season`, "EXPECTED_RESULT")
})

test_that("session", {
  # tests for the property `session` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`session`, "EXPECTED_RESULT")
})

test_that("game_id", {
  # tests for the property `game_id` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`game_id`, "EXPECTED_RESULT")
})

test_that("event_idx", {
  # tests for the property `event_idx` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`event_idx`, "EXPECTED_RESULT")
})

test_that("period", {
  # tests for the property `period` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`period`, "EXPECTED_RESULT")
})

test_that("period_seconds", {
  # tests for the property `period_seconds` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`period_seconds`, "EXPECTED_RESULT")
})

test_that("game_seconds", {
  # tests for the property `game_seconds` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`game_seconds`, "EXPECTED_RESULT")
})

test_that("strength_state", {
  # tests for the property `strength_state` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`strength_state`, "EXPECTED_RESULT")
})

test_that("event_team", {
  # tests for the property `event_team` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`event_team`, "EXPECTED_RESULT")
})

test_that("opp_team", {
  # tests for the property `opp_team` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`opp_team`, "EXPECTED_RESULT")
})

test_that("event", {
  # tests for the property `event` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`event`, "EXPECTED_RESULT")
})

test_that("description", {
  # tests for the property `description` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`description`, "EXPECTED_RESULT")
})

test_that("zone", {
  # tests for the property `zone` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`zone`, "EXPECTED_RESULT")
})

test_that("coords_x", {
  # tests for the property `coords_x` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`coords_x`, "EXPECTED_RESULT")
})

test_that("coords_y", {
  # tests for the property `coords_y` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`coords_y`, "EXPECTED_RESULT")
})

test_that("danger", {
  # tests for the property `danger` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`danger`, "EXPECTED_RESULT")
})

test_that("high_danger", {
  # tests for the property `high_danger` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`high_danger`, "EXPECTED_RESULT")
})

test_that("player_1_api_id", {
  # tests for the property `player_1_api_id` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`player_1_api_id`, "EXPECTED_RESULT")
})

test_that("player_1_type", {
  # tests for the property `player_1_type` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`player_1_type`, "EXPECTED_RESULT")
})

test_that("player_2_api_id", {
  # tests for the property `player_2_api_id` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`player_2_api_id`, "EXPECTED_RESULT")
})

test_that("player_2_type", {
  # tests for the property `player_2_type` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`player_2_type`, "EXPECTED_RESULT")
})

test_that("player_3_api_id", {
  # tests for the property `player_3_api_id` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`player_3_api_id`, "EXPECTED_RESULT")
})

test_that("player_3_type", {
  # tests for the property `player_3_type` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`player_3_type`, "EXPECTED_RESULT")
})

test_that("score_state", {
  # tests for the property `score_state` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`score_state`, "EXPECTED_RESULT")
})

test_that("score_diff", {
  # tests for the property `score_diff` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`score_diff`, "EXPECTED_RESULT")
})

test_that("forwards_percent", {
  # tests for the property `forwards_percent` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`forwards_percent`, "EXPECTED_RESULT")
})

test_that("opp_forwards_percent", {
  # tests for the property `opp_forwards_percent` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`opp_forwards_percent`, "EXPECTED_RESULT")
})

test_that("shot_type", {
  # tests for the property `shot_type` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`shot_type`, "EXPECTED_RESULT")
})

test_that("event_length", {
  # tests for the property `event_length` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`event_length`, "EXPECTED_RESULT")
})

test_that("event_distance", {
  # tests for the property `event_distance` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`event_distance`, "EXPECTED_RESULT")
})

test_that("pbp_distance", {
  # tests for the property `pbp_distance` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`pbp_distance`, "EXPECTED_RESULT")
})

test_that("event_angle", {
  # tests for the property `event_angle` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`event_angle`, "EXPECTED_RESULT")
})

test_that("penalty", {
  # tests for the property `penalty` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`penalty`, "EXPECTED_RESULT")
})

test_that("penalty_length", {
  # tests for the property `penalty_length` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`penalty_length`, "EXPECTED_RESULT")
})

test_that("event_team_skaters", {
  # tests for the property `event_team_skaters` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`event_team_skaters`, "EXPECTED_RESULT")
})

test_that("teammates_api_id", {
  # tests for the property `teammates_api_id` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`teammates_api_id`, "EXPECTED_RESULT")
})

test_that("own_goalie_api_id", {
  # tests for the property `own_goalie_api_id` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`own_goalie_api_id`, "EXPECTED_RESULT")
})

test_that("forwards_api_id", {
  # tests for the property `forwards_api_id` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`forwards_api_id`, "EXPECTED_RESULT")
})

test_that("forwards_count", {
  # tests for the property `forwards_count` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`forwards_count`, "EXPECTED_RESULT")
})

test_that("defense_api_id", {
  # tests for the property `defense_api_id` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`defense_api_id`, "EXPECTED_RESULT")
})

test_that("defense_count", {
  # tests for the property `defense_count` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`defense_count`, "EXPECTED_RESULT")
})

test_that("opp_strength_state", {
  # tests for the property `opp_strength_state` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`opp_strength_state`, "EXPECTED_RESULT")
})

test_that("opp_score_state", {
  # tests for the property `opp_score_state` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`opp_score_state`, "EXPECTED_RESULT")
})

test_that("opp_score_diff", {
  # tests for the property `opp_score_diff` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`opp_score_diff`, "EXPECTED_RESULT")
})

test_that("opp_team_skaters", {
  # tests for the property `opp_team_skaters` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`opp_team_skaters`, "EXPECTED_RESULT")
})

test_that("opp_team_on_api_id", {
  # tests for the property `opp_team_on_api_id` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`opp_team_on_api_id`, "EXPECTED_RESULT")
})

test_that("opp_goalie_api_id", {
  # tests for the property `opp_goalie_api_id` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`opp_goalie_api_id`, "EXPECTED_RESULT")
})

test_that("opp_forwards_api_id", {
  # tests for the property `opp_forwards_api_id` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`opp_forwards_api_id`, "EXPECTED_RESULT")
})

test_that("opp_forwards_count", {
  # tests for the property `opp_forwards_count` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`opp_forwards_count`, "EXPECTED_RESULT")
})

test_that("opp_defense_api_id", {
  # tests for the property `opp_defense_api_id` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`opp_defense_api_id`, "EXPECTED_RESULT")
})

test_that("opp_defense_count", {
  # tests for the property `opp_defense_count` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`opp_defense_count`, "EXPECTED_RESULT")
})

test_that("home_score", {
  # tests for the property `home_score` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`home_score`, "EXPECTED_RESULT")
})

test_that("home_score_diff", {
  # tests for the property `home_score_diff` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`home_score_diff`, "EXPECTED_RESULT")
})

test_that("away_score", {
  # tests for the property `away_score` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`away_score`, "EXPECTED_RESULT")
})

test_that("away_score_diff", {
  # tests for the property `away_score_diff` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`away_score_diff`, "EXPECTED_RESULT")
})

test_that("is_home", {
  # tests for the property `is_home` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`is_home`, "EXPECTED_RESULT")
})

test_that("is_away", {
  # tests for the property `is_away` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`is_away`, "EXPECTED_RESULT")
})

test_that("home_skaters", {
  # tests for the property `home_skaters` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`home_skaters`, "EXPECTED_RESULT")
})

test_that("away_skaters", {
  # tests for the property `away_skaters` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`away_skaters`, "EXPECTED_RESULT")
})

test_that("home_on_api_id", {
  # tests for the property `home_on_api_id` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`home_on_api_id`, "EXPECTED_RESULT")
})

test_that("away_on_api_id", {
  # tests for the property `away_on_api_id` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`away_on_api_id`, "EXPECTED_RESULT")
})

test_that("home_forwards_api_id", {
  # tests for the property `home_forwards_api_id` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`home_forwards_api_id`, "EXPECTED_RESULT")
})

test_that("home_forwards_count", {
  # tests for the property `home_forwards_count` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`home_forwards_count`, "EXPECTED_RESULT")
})

test_that("home_forwards_percent", {
  # tests for the property `home_forwards_percent` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`home_forwards_percent`, "EXPECTED_RESULT")
})

test_that("home_defense_api_id", {
  # tests for the property `home_defense_api_id` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`home_defense_api_id`, "EXPECTED_RESULT")
})

test_that("home_defense_count", {
  # tests for the property `home_defense_count` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`home_defense_count`, "EXPECTED_RESULT")
})

test_that("home_goalie_api_id", {
  # tests for the property `home_goalie_api_id` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`home_goalie_api_id`, "EXPECTED_RESULT")
})

test_that("away_forwards_api_id", {
  # tests for the property `away_forwards_api_id` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`away_forwards_api_id`, "EXPECTED_RESULT")
})

test_that("away_forwards_count", {
  # tests for the property `away_forwards_count` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`away_forwards_count`, "EXPECTED_RESULT")
})

test_that("away_forwards_percent", {
  # tests for the property `away_forwards_percent` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`away_forwards_percent`, "EXPECTED_RESULT")
})

test_that("away_defense_api_id", {
  # tests for the property `away_defense_api_id` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`away_defense_api_id`, "EXPECTED_RESULT")
})

test_that("away_defense_count", {
  # tests for the property `away_defense_count` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`away_defense_count`, "EXPECTED_RESULT")
})

test_that("away_goalie_api_id", {
  # tests for the property `away_goalie_api_id` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`away_goalie_api_id`, "EXPECTED_RESULT")
})

test_that("change_on_count", {
  # tests for the property `change_on_count` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`change_on_count`, "EXPECTED_RESULT")
})

test_that("change_off_count", {
  # tests for the property `change_off_count` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`change_off_count`, "EXPECTED_RESULT")
})

test_that("change_on_api_id", {
  # tests for the property `change_on_api_id` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`change_on_api_id`, "EXPECTED_RESULT")
})

test_that("change_off_api_id", {
  # tests for the property `change_off_api_id` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`change_off_api_id`, "EXPECTED_RESULT")
})

test_that("change_on_forwards_count", {
  # tests for the property `change_on_forwards_count` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`change_on_forwards_count`, "EXPECTED_RESULT")
})

test_that("change_off_forwards_count", {
  # tests for the property `change_off_forwards_count` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`change_off_forwards_count`, "EXPECTED_RESULT")
})

test_that("change_on_forwards_api_id", {
  # tests for the property `change_on_forwards_api_id` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`change_on_forwards_api_id`, "EXPECTED_RESULT")
})

test_that("change_off_forwards_api_id", {
  # tests for the property `change_off_forwards_api_id` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`change_off_forwards_api_id`, "EXPECTED_RESULT")
})

test_that("change_on_defense_count", {
  # tests for the property `change_on_defense_count` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`change_on_defense_count`, "EXPECTED_RESULT")
})

test_that("change_off_defense_count", {
  # tests for the property `change_off_defense_count` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`change_off_defense_count`, "EXPECTED_RESULT")
})

test_that("change_on_defense_api_id", {
  # tests for the property `change_on_defense_api_id` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`change_on_defense_api_id`, "EXPECTED_RESULT")
})

test_that("change_off_defense_api_id", {
  # tests for the property `change_off_defense_api_id` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`change_off_defense_api_id`, "EXPECTED_RESULT")
})

test_that("change_on_goalie_count", {
  # tests for the property `change_on_goalie_count` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`change_on_goalie_count`, "EXPECTED_RESULT")
})

test_that("change_off_goalie_count", {
  # tests for the property `change_off_goalie_count` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`change_off_goalie_count`, "EXPECTED_RESULT")
})

test_that("change_on_goalie_api_id", {
  # tests for the property `change_on_goalie_api_id` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`change_on_goalie_api_id`, "EXPECTED_RESULT")
})

test_that("change_off_goalie_api_id", {
  # tests for the property `change_off_goalie_api_id` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`change_off_goalie_api_id`, "EXPECTED_RESULT")
})

test_that("base_xg", {
  # tests for the property `base_xg` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`base_xg`, "EXPECTED_RESULT")
})

test_that("base_xg_adj", {
  # tests for the property `base_xg_adj` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`base_xg_adj`, "EXPECTED_RESULT")
})

test_that("context_xg", {
  # tests for the property `context_xg` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`context_xg`, "EXPECTED_RESULT")
})

test_that("context_xg_adj", {
  # tests for the property `context_xg_adj` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`context_xg_adj`, "EXPECTED_RESULT")
})

test_that("pred_goal", {
  # tests for the property `pred_goal` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`pred_goal`, "EXPECTED_RESULT")
})

test_that("pred_goal_adj", {
  # tests for the property `pred_goal_adj` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`pred_goal_adj`, "EXPECTED_RESULT")
})

test_that("goal", {
  # tests for the property `goal` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`goal`, "EXPECTED_RESULT")
})

test_that("goal_adj", {
  # tests for the property `goal_adj` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`goal_adj`, "EXPECTED_RESULT")
})

test_that("hd_goal", {
  # tests for the property `hd_goal` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`hd_goal`, "EXPECTED_RESULT")
})

test_that("shot", {
  # tests for the property `shot` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`shot`, "EXPECTED_RESULT")
})

test_that("shot_adj", {
  # tests for the property `shot_adj` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`shot_adj`, "EXPECTED_RESULT")
})

test_that("hd_shot", {
  # tests for the property `hd_shot` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`hd_shot`, "EXPECTED_RESULT")
})

test_that("miss", {
  # tests for the property `miss` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`miss`, "EXPECTED_RESULT")
})

test_that("miss_adj", {
  # tests for the property `miss_adj` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`miss_adj`, "EXPECTED_RESULT")
})

test_that("hd_miss", {
  # tests for the property `hd_miss` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`hd_miss`, "EXPECTED_RESULT")
})

test_that("fenwick", {
  # tests for the property `fenwick` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`fenwick`, "EXPECTED_RESULT")
})

test_that("fenwick_adj", {
  # tests for the property `fenwick_adj` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`fenwick_adj`, "EXPECTED_RESULT")
})

test_that("hd_fenwick", {
  # tests for the property `hd_fenwick` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`hd_fenwick`, "EXPECTED_RESULT")
})

test_that("corsi", {
  # tests for the property `corsi` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`corsi`, "EXPECTED_RESULT")
})

test_that("corsi_adj", {
  # tests for the property `corsi_adj` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`corsi_adj`, "EXPECTED_RESULT")
})

test_that("block", {
  # tests for the property `block` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`block`, "EXPECTED_RESULT")
})

test_that("block_adj", {
  # tests for the property `block_adj` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`block_adj`, "EXPECTED_RESULT")
})

test_that("teammate_block", {
  # tests for the property `teammate_block` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`teammate_block`, "EXPECTED_RESULT")
})

test_that("teammate_block_adj", {
  # tests for the property `teammate_block_adj` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`teammate_block_adj`, "EXPECTED_RESULT")
})

test_that("hit", {
  # tests for the property `hit` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`hit`, "EXPECTED_RESULT")
})

test_that("give", {
  # tests for the property `give` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`give`, "EXPECTED_RESULT")
})

test_that("take", {
  # tests for the property `take` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`take`, "EXPECTED_RESULT")
})

test_that("fac", {
  # tests for the property `fac` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`fac`, "EXPECTED_RESULT")
})

test_that("penl", {
  # tests for the property `penl` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`penl`, "EXPECTED_RESULT")
})

test_that("change", {
  # tests for the property `change` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`change`, "EXPECTED_RESULT")
})

test_that("stop", {
  # tests for the property `stop` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`stop`, "EXPECTED_RESULT")
})

test_that("chl", {
  # tests for the property `chl` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`chl`, "EXPECTED_RESULT")
})

test_that("ozf", {
  # tests for the property `ozf` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`ozf`, "EXPECTED_RESULT")
})

test_that("nzf", {
  # tests for the property `nzf` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`nzf`, "EXPECTED_RESULT")
})

test_that("dzf", {
  # tests for the property `dzf` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`dzf`, "EXPECTED_RESULT")
})

test_that("ozc", {
  # tests for the property `ozc` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`ozc`, "EXPECTED_RESULT")
})

test_that("nzc", {
  # tests for the property `nzc` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`nzc`, "EXPECTED_RESULT")
})

test_that("dzc", {
  # tests for the property `dzc` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`dzc`, "EXPECTED_RESULT")
})

test_that("otf", {
  # tests for the property `otf` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`otf`, "EXPECTED_RESULT")
})

test_that("pen0", {
  # tests for the property `pen0` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`pen0`, "EXPECTED_RESULT")
})

test_that("pen2", {
  # tests for the property `pen2` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`pen2`, "EXPECTED_RESULT")
})

test_that("pen4", {
  # tests for the property `pen4` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`pen4`, "EXPECTED_RESULT")
})

test_that("pen5", {
  # tests for the property `pen5` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`pen5`, "EXPECTED_RESULT")
})

test_that("pen10", {
  # tests for the property `pen10` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`pen10`, "EXPECTED_RESULT")
})

test_that("player", {
  # tests for the property `player` (PlayerPublic)

  # uncomment below to test the property
  #expect_equal(model.instance$`player`, "EXPECTED_RESULT")
})

test_that("game", {
  # tests for the property `game` (GamePublic)

  # uncomment below to test the property
  #expect_equal(model.instance$`game`, "EXPECTED_RESULT")
})
