# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test PlayersApi")

api_instance <- PlayersApi$new()

test_that("ReadPlayer", {
  # tests for ReadPlayer
  # base path: https://api.chickenstats.com
  # Read Player
  # @param api_id integer 
  # @return [PlayerPublic]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ReadPlayers", {
  # tests for ReadPlayers
  # base path: https://api.chickenstats.com
  # Read Players
  # @param name character  (optional)
  # @param position character  (optional)
  # @param eh_id character  (optional)
  # @param limit integer  (optional)
  # @param offset integer  (optional)
  # @return [PlayerResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
