# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ChangesPublic")

model_instance <- ChangesPublic$new()

test_that("season", {
  # tests for the property `season` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`season`, "EXPECTED_RESULT")
})

test_that("session", {
  # tests for the property `session` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`session`, "EXPECTED_RESULT")
})

test_that("game_id", {
  # tests for the property `game_id` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`game_id`, "EXPECTED_RESULT")
})

test_that("event_team", {
  # tests for the property `event_team` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`event_team`, "EXPECTED_RESULT")
})

test_that("event", {
  # tests for the property `event` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`event`, "EXPECTED_RESULT")
})

test_that("event_type", {
  # tests for the property `event_type` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`event_type`, "EXPECTED_RESULT")
})

test_that("description", {
  # tests for the property `description` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`description`, "EXPECTED_RESULT")
})

test_that("period", {
  # tests for the property `period` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`period`, "EXPECTED_RESULT")
})

test_that("period_seconds", {
  # tests for the property `period_seconds` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`period_seconds`, "EXPECTED_RESULT")
})

test_that("game_seconds", {
  # tests for the property `game_seconds` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`game_seconds`, "EXPECTED_RESULT")
})

test_that("change_on_count", {
  # tests for the property `change_on_count` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`change_on_count`, "EXPECTED_RESULT")
})

test_that("change_off_count", {
  # tests for the property `change_off_count` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`change_off_count`, "EXPECTED_RESULT")
})

test_that("change_on_api_id", {
  # tests for the property `change_on_api_id` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`change_on_api_id`, "EXPECTED_RESULT")
})

test_that("change_off_api_id", {
  # tests for the property `change_off_api_id` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`change_off_api_id`, "EXPECTED_RESULT")
})

test_that("change_on_forwards_count", {
  # tests for the property `change_on_forwards_count` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`change_on_forwards_count`, "EXPECTED_RESULT")
})

test_that("change_off_forwards_count", {
  # tests for the property `change_off_forwards_count` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`change_off_forwards_count`, "EXPECTED_RESULT")
})

test_that("change_on_forwards_api_id", {
  # tests for the property `change_on_forwards_api_id` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`change_on_forwards_api_id`, "EXPECTED_RESULT")
})

test_that("change_off_forwards_api_id", {
  # tests for the property `change_off_forwards_api_id` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`change_off_forwards_api_id`, "EXPECTED_RESULT")
})

test_that("change_on_defense_count", {
  # tests for the property `change_on_defense_count` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`change_on_defense_count`, "EXPECTED_RESULT")
})

test_that("change_off_defense_count", {
  # tests for the property `change_off_defense_count` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`change_off_defense_count`, "EXPECTED_RESULT")
})

test_that("change_on_defense_api_id", {
  # tests for the property `change_on_defense_api_id` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`change_on_defense_api_id`, "EXPECTED_RESULT")
})

test_that("change_off_defense_api_id", {
  # tests for the property `change_off_defense_api_id` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`change_off_defense_api_id`, "EXPECTED_RESULT")
})

test_that("change_on_goalie_count", {
  # tests for the property `change_on_goalie_count` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`change_on_goalie_count`, "EXPECTED_RESULT")
})

test_that("change_off_goalie_count", {
  # tests for the property `change_off_goalie_count` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`change_off_goalie_count`, "EXPECTED_RESULT")
})

test_that("change_on_goalie_api_id", {
  # tests for the property `change_on_goalie_api_id` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`change_on_goalie_api_id`, "EXPECTED_RESULT")
})

test_that("change_off_goalie_api_id", {
  # tests for the property `change_off_goalie_api_id` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`change_off_goalie_api_id`, "EXPECTED_RESULT")
})

test_that("is_home", {
  # tests for the property `is_home` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`is_home`, "EXPECTED_RESULT")
})

test_that("game", {
  # tests for the property `game` (GamePublic)

  # uncomment below to test the property
  #expect_equal(model.instance$`game`, "EXPECTED_RESULT")
})
