# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test LiveApi")

api_instance <- LiveApi$new()

test_that("ReadLiveGames", {
  # tests for ReadLiveGames
  # base path: https://api.chickenstats.com
  # Read Live Games
  # @return [array[LiveGamesPublic]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ReadLivePbp", {
  # tests for ReadLivePbp
  # base path: https://api.chickenstats.com
  # Read Live Pbp
  # @param game_id array[integer]  (optional)
  # @param limit integer  (optional)
  # @param offset integer  (optional)
  # @return [LivePbpResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
