# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test UserUpdate")

model_instance <- UserUpdate$new()

test_that("email", {
  # tests for the property `email` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`email`, "EXPECTED_RESULT")
})

test_that("is_active", {
  # tests for the property `is_active` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`is_active`, "EXPECTED_RESULT")
})

test_that("is_superuser", {
  # tests for the property `is_superuser` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`is_superuser`, "EXPECTED_RESULT")
})

test_that("is_contributor", {
  # tests for the property `is_contributor` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`is_contributor`, "EXPECTED_RESULT")
})

test_that("full_name", {
  # tests for the property `full_name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`full_name`, "EXPECTED_RESULT")
})

test_that("tier", {
  # tests for the property `tier` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`tier`, "EXPECTED_RESULT")
})

test_that("password", {
  # tests for the property `password` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`password`, "EXPECTED_RESULT")
})
