# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test StandingsPublic")

model_instance <- StandingsPublic$new()

test_that("season", {
  # tests for the property `season` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`season`, "EXPECTED_RESULT")
})

test_that("team", {
  # tests for the property `team` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`team`, "EXPECTED_RESULT")
})

test_that("division_rank", {
  # tests for the property `division_rank` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`division_rank`, "EXPECTED_RESULT")
})

test_that("conference_rank", {
  # tests for the property `conference_rank` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`conference_rank`, "EXPECTED_RESULT")
})

test_that("league_rank", {
  # tests for the property `league_rank` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`league_rank`, "EXPECTED_RESULT")
})

test_that("division_rank_home", {
  # tests for the property `division_rank_home` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`division_rank_home`, "EXPECTED_RESULT")
})

test_that("division_rank_road", {
  # tests for the property `division_rank_road` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`division_rank_road`, "EXPECTED_RESULT")
})

test_that("division_rank_last10", {
  # tests for the property `division_rank_last10` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`division_rank_last10`, "EXPECTED_RESULT")
})

test_that("conference_rank_home", {
  # tests for the property `conference_rank_home` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`conference_rank_home`, "EXPECTED_RESULT")
})

test_that("conference_rank_road", {
  # tests for the property `conference_rank_road` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`conference_rank_road`, "EXPECTED_RESULT")
})

test_that("conference_rank_last10", {
  # tests for the property `conference_rank_last10` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`conference_rank_last10`, "EXPECTED_RESULT")
})

test_that("league_rank_home", {
  # tests for the property `league_rank_home` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`league_rank_home`, "EXPECTED_RESULT")
})

test_that("league_rank_road", {
  # tests for the property `league_rank_road` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`league_rank_road`, "EXPECTED_RESULT")
})

test_that("league_rank_last10", {
  # tests for the property `league_rank_last10` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`league_rank_last10`, "EXPECTED_RESULT")
})

test_that("wildcard_rank", {
  # tests for the property `wildcard_rank` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`wildcard_rank`, "EXPECTED_RESULT")
})

test_that("points", {
  # tests for the property `points` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`points`, "EXPECTED_RESULT")
})

test_that("points_percentage", {
  # tests for the property `points_percentage` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`points_percentage`, "EXPECTED_RESULT")
})

test_that("wins", {
  # tests for the property `wins` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`wins`, "EXPECTED_RESULT")
})

test_that("losses", {
  # tests for the property `losses` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`losses`, "EXPECTED_RESULT")
})

test_that("otl", {
  # tests for the property `otl` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`otl`, "EXPECTED_RESULT")
})

test_that("games_played", {
  # tests for the property `games_played` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`games_played`, "EXPECTED_RESULT")
})

test_that("goals_scored", {
  # tests for the property `goals_scored` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`goals_scored`, "EXPECTED_RESULT")
})

test_that("goals_against", {
  # tests for the property `goals_against` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`goals_against`, "EXPECTED_RESULT")
})

test_that("streak", {
  # tests for the property `streak` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`streak`, "EXPECTED_RESULT")
})

test_that("pp_rank_division", {
  # tests for the property `pp_rank_division` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`pp_rank_division`, "EXPECTED_RESULT")
})

test_that("pp_rank_conference", {
  # tests for the property `pp_rank_conference` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`pp_rank_conference`, "EXPECTED_RESULT")
})

test_that("pp_rank_league", {
  # tests for the property `pp_rank_league` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`pp_rank_league`, "EXPECTED_RESULT")
})

test_that("last_updated", {
  # tests for the property `last_updated` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`last_updated`, "EXPECTED_RESULT")
})
