# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ProgrammaticCredentials")

model_instance <- ProgrammaticCredentials$new()

test_that("cf_client_id", {
  # tests for the property `cf_client_id` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`cf_client_id`, "EXPECTED_RESULT")
})

test_that("cf_client_secret", {
  # tests for the property `cf_client_secret` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`cf_client_secret`, "EXPECTED_RESULT")
})

test_that("token_endpoint", {
  # tests for the property `token_endpoint` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`token_endpoint`, "EXPECTED_RESULT")
})

test_that("note", {
  # tests for the property `note` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`note`, "EXPECTED_RESULT")
})
