# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test RosterPublic")

model_instance <- RosterPublic$new()

test_that("game_id", {
  # tests for the property `game_id` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`game_id`, "EXPECTED_RESULT")
})

test_that("api_id", {
  # tests for the property `api_id` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`api_id`, "EXPECTED_RESULT")
})

test_that("team", {
  # tests for the property `team` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`team`, "EXPECTED_RESULT")
})

test_that("jersey", {
  # tests for the property `jersey` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`jersey`, "EXPECTED_RESULT")
})

test_that("position", {
  # tests for the property `position` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`position`, "EXPECTED_RESULT")
})

test_that("starter", {
  # tests for the property `starter` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`starter`, "EXPECTED_RESULT")
})

test_that("rookie", {
  # tests for the property `rookie` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`rookie`, "EXPECTED_RESULT")
})

test_that("captain", {
  # tests for the property `captain` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`captain`, "EXPECTED_RESULT")
})

test_that("alternate_captain", {
  # tests for the property `alternate_captain` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`alternate_captain`, "EXPECTED_RESULT")
})

test_that("status", {
  # tests for the property `status` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`status`, "EXPECTED_RESULT")
})

test_that("active", {
  # tests for the property `active` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`active`, "EXPECTED_RESULT")
})

test_that("player", {
  # tests for the property `player` (PlayerPublic)

  # uncomment below to test the property
  #expect_equal(model.instance$`player`, "EXPECTED_RESULT")
})

test_that("game", {
  # tests for the property `game` (GamePublic)

  # uncomment below to test the property
  #expect_equal(model.instance$`game`, "EXPECTED_RESULT")
})
