# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test BillingApi")

api_instance <- BillingApi$new()

test_that("CreateCheckoutSession", {
  # tests for CreateCheckoutSession
  # base path: https://api.chickenstats.com
  # Create Checkout Session
  # Create a Stripe Checkout session for the given tier and return its URL.  Created via a direct server-side Stripe API call rather than the Firebase extension&#39;s client-SDK pattern (Firestore-triggered function, meant for a JS SPA) -- this project&#39;s frontend is server-rendered. The extension&#39;s handleWebhookEvents function still processes the resulting checkout.session.completed event and sets the stripeRole claim, since Stripe fires the same webhook regardless of how the session was created.
  # @param tier character 
  # @return [map(character)]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("CreatePortalSession", {
  # tests for CreatePortalSession
  # base path: https://api.chickenstats.com
  # Create Portal Session
  # Create a Stripe customer billing-portal session and return its URL.  Finds the customer by email -- the Firebase extension already creates a Stripe customer per Firebase user (\&quot;Sync new users to Stripe customers\&quot;), so no separate customer-ID storage is needed here.
  # @return [map(character)]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
