# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test RapmApi")

api_instance <- RapmApi$new()

test_that("ReadRapm", {
  # tests for ReadRapm
  # base path: https://api.chickenstats.com
  # Read Rapm
  # @param season array[integer]  (optional)
  # @param sessions array[character]  (optional)
  # @param api_id array[integer]  (optional)
  # @param name array[character]  (optional)
  # @param team array[character]  (optional)
  # @param situation array[character]  (optional)
  # @param limit integer  (optional)
  # @param offset integer  (optional)
  # @return [RapmResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
