# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test StatsApi")

api_instance <- StatsApi$new()

test_that("ReadGameStats", {
  # tests for ReadGameStats
  # base path: https://api.chickenstats.com
  # Read Game Stats
  # @param season array[integer]  (optional)
  # @param sessions array[character]  (optional)
  # @param game_id array[integer]  (optional)
  # @param level character  (optional)
  # @param player array[character]  (optional)
  # @param api_id array[integer]  (optional)
  # @param eh_id array[character]  (optional)
  # @param team array[character]  (optional)
  # @param opp_team array[character]  (optional)
  # @param strength_state array[character]  (optional)
  # @param score_state character  (optional)
  # @param teammates character  (optional)
  # @param opposition character  (optional)
  # @param limit integer  (optional)
  # @param offset integer  (optional)
  # @return [StatsGameResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ReadSeasonStats", {
  # tests for ReadSeasonStats
  # base path: https://api.chickenstats.com
  # Read Season Stats
  # @param season array[integer]  (optional)
  # @param sessions array[character]  (optional)
  # @param player array[character]  (optional)
  # @param api_id array[integer]  (optional)
  # @param eh_id array[character]  (optional)
  # @param team array[character]  (optional)
  # @param opp_team array[character]  (optional)
  # @param strength_state array[character]  (optional)
  # @param score_state character  (optional)
  # @param teammates character  (optional)
  # @param opposition character  (optional)
  # @param limit integer  (optional)
  # @param offset integer  (optional)
  # @return [StatsSeasonResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ReadStatsGameIds", {
  # tests for ReadStatsGameIds
  # base path: https://api.chickenstats.com
  # Read Stats Game Ids
  # @param season array[integer]  (optional)
  # @param sessions array[character]  (optional)
  # @return [array[integer]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
