#' chickenstats API
#'
#' API for downloading NHL data
#'
#' The version of the OpenAPI document: 0.1.3
#' Contact: chicken@chickenandstats.com
#' Generated by: https://openapi-generator.tech
#'
#' @docType class
#' @title Lines operations
#' @description LinesApi
#' @format An \code{R6Class} generator object
#' @field api_client Handles the client-server communication.
#'
#' @examples
#' \dontrun{
#' ####################  ReadGameLines  ####################
#'
#' library(chickenstats.api)
#' var_season <- c(123) # array[integer] |  (Optional)
#' var_sessions <- c("R") # array[character] |  (Optional)
#' var_game_id <- c(123) # array[integer] |  (Optional)
#' var_team <- c("inner_example") # array[character] |  (Optional)
#' var_opp_team <- c("inner_example") # array[character] |  (Optional)
#' var_strength_state <- c("5v5") # array[character] |  (Optional)
#' var_score_state <- "score_state_example" # character |  (Optional)
#' var_level <- "level_example" # character |  (Optional)
#' var_linemates <- "linemates_example" # character |  (Optional)
#' var_opposition <- "opposition_example" # character |  (Optional)
#' var_limit <- 10000 # integer |  (Optional)
#' var_offset <- 0 # integer |  (Optional)
#'
#' #Read Game Lines
#' api_instance <- LinesApi$new()
#'
#' # Configure OAuth2 access token for authorization: OAuth2PasswordBearer
#' api_instance$api_client$access_token <- Sys.getenv("ACCESS_TOKEN")
#'
#' # to save the result into a file, simply add the optional `data_file` parameter, e.g.
#' # result <- api_instance$ReadGameLines(season = var_season, sessions = var_sessions, game_id = var_game_id, team = var_team, opp_team = var_opp_team, strength_state = var_strength_state, score_state = var_score_state, level = var_level, linemates = var_linemates, opposition = var_opposition, limit = var_limit, offset = var_offsetdata_file = "result.txt")
#' result <- api_instance$ReadGameLines(season = var_season, sessions = var_sessions, game_id = var_game_id, team = var_team, opp_team = var_opp_team, strength_state = var_strength_state, score_state = var_score_state, level = var_level, linemates = var_linemates, opposition = var_opposition, limit = var_limit, offset = var_offset)
#' dput(result)
#'
#'
#' ####################  ReadLineIds  ####################
#'
#' library(chickenstats.api)
#' var_season <- c(123) # array[integer] |  (Optional)
#' var_sessions <- c("R") # array[character] |  (Optional)
#'
#' #Read Line Ids
#' api_instance <- LinesApi$new()
#'
#' # Configure OAuth2 access token for authorization: OAuth2PasswordBearer
#' api_instance$api_client$access_token <- Sys.getenv("ACCESS_TOKEN")
#'
#' # to save the result into a file, simply add the optional `data_file` parameter, e.g.
#' # result <- api_instance$ReadLineIds(season = var_season, sessions = var_sessionsdata_file = "result.txt")
#' result <- api_instance$ReadLineIds(season = var_season, sessions = var_sessions)
#' dput(result)
#'
#'
#' ####################  ReadLinesGameIds  ####################
#'
#' library(chickenstats.api)
#' var_season <- c(123) # array[integer] |  (Optional)
#' var_sessions <- c("R") # array[character] |  (Optional)
#'
#' #Read Lines Game Ids
#' api_instance <- LinesApi$new()
#'
#' # Configure OAuth2 access token for authorization: OAuth2PasswordBearer
#' api_instance$api_client$access_token <- Sys.getenv("ACCESS_TOKEN")
#'
#' # to save the result into a file, simply add the optional `data_file` parameter, e.g.
#' # result <- api_instance$ReadLinesGameIds(season = var_season, sessions = var_sessionsdata_file = "result.txt")
#' result <- api_instance$ReadLinesGameIds(season = var_season, sessions = var_sessions)
#' dput(result)
#'
#'
#' ####################  ReadSeasonLines  ####################
#'
#' library(chickenstats.api)
#' var_season <- c(123) # array[integer] |  (Optional)
#' var_sessions <- c("R") # array[character] |  (Optional)
#' var_team <- c("inner_example") # array[character] |  (Optional)
#' var_opp_team <- c("inner_example") # array[character] |  (Optional)
#' var_strength_state <- c("5v5") # array[character] |  (Optional)
#' var_score_state <- "score_state_example" # character |  (Optional)
#' var_linemates <- "linemates_example" # character |  (Optional)
#' var_opposition <- "opposition_example" # character |  (Optional)
#' var_limit <- 10000 # integer |  (Optional)
#' var_offset <- 0 # integer |  (Optional)
#'
#' #Read Season Lines
#' api_instance <- LinesApi$new()
#'
#' # Configure OAuth2 access token for authorization: OAuth2PasswordBearer
#' api_instance$api_client$access_token <- Sys.getenv("ACCESS_TOKEN")
#'
#' # to save the result into a file, simply add the optional `data_file` parameter, e.g.
#' # result <- api_instance$ReadSeasonLines(season = var_season, sessions = var_sessions, team = var_team, opp_team = var_opp_team, strength_state = var_strength_state, score_state = var_score_state, linemates = var_linemates, opposition = var_opposition, limit = var_limit, offset = var_offsetdata_file = "result.txt")
#' result <- api_instance$ReadSeasonLines(season = var_season, sessions = var_sessions, team = var_team, opp_team = var_opp_team, strength_state = var_strength_state, score_state = var_score_state, linemates = var_linemates, opposition = var_opposition, limit = var_limit, offset = var_offset)
#' dput(result)
#'
#'
#' }
#' @importFrom R6 R6Class
#' @importFrom base64enc base64encode
#' @export
LinesApi <- R6::R6Class(
  "LinesApi",
  public = list(
    api_client = NULL,

    #' @description
    #' Initialize a new LinesApi.
    #'
    #' @param api_client An instance of API client.
    initialize = function(api_client) {
      if (!missing(api_client)) {
        self$api_client <- api_client
      } else {
        self$api_client <- ApiClient$new()
      }
    },

    #' @description
    #' Read Game Lines
    #'
    #' @param season (optional) No description
    #' @param sessions (optional) No description
    #' @param game_id (optional) No description
    #' @param team (optional) No description
    #' @param opp_team (optional) No description
    #' @param strength_state (optional) No description
    #' @param score_state (optional) No description
    #' @param level (optional) No description
    #' @param linemates (optional) No description
    #' @param opposition (optional) No description
    #' @param limit (optional) No description (default value: 10000)
    #' @param offset (optional) No description (default value: 0)
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #'
    #' @return LinesGameResponse
    ReadGameLines = function(season = NULL, sessions = NULL, game_id = NULL, team = NULL, opp_team = NULL, strength_state = NULL, score_state = NULL, level = NULL, linemates = NULL, opposition = NULL, limit = 10000, offset = 0, data_file = NULL, ...) {
      local_var_response <- self$ReadGameLinesWithHttpInfo(season, sessions, game_id, team, opp_team, strength_state, score_state, level, linemates, opposition, limit, offset, data_file = data_file, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        return(local_var_response$content)
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        return(local_var_response)
      }
    },

    #' @description
    #' Read Game Lines
    #'
    #' @param season (optional) No description
    #' @param sessions (optional) No description
    #' @param game_id (optional) No description
    #' @param team (optional) No description
    #' @param opp_team (optional) No description
    #' @param strength_state (optional) No description
    #' @param score_state (optional) No description
    #' @param level (optional) No description
    #' @param linemates (optional) No description
    #' @param opposition (optional) No description
    #' @param limit (optional) No description (default value: 10000)
    #' @param offset (optional) No description (default value: 0)
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #'
    #' @return API response (LinesGameResponse) with additional information such as HTTP status code, headers
    ReadGameLinesWithHttpInfo = function(season = NULL, sessions = NULL, game_id = NULL, team = NULL, opp_team = NULL, strength_state = NULL, score_state = NULL, level = NULL, linemates = NULL, opposition = NULL, limit = 10000, offset = 0, data_file = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE











      if (`limit` > 50000) {
        stop("Invalid value for `limit` when calling LinesApi$ReadGameLines, must be smaller than or equal to 50000.")
      }
      if (`limit` < 1) {
        stop("Invalid value for `limit` when calling LinesApi$ReadGameLines, must be bigger than or equal to 1.")
      }

      if (`offset` < 0) {
        stop("Invalid value for `offset` when calling LinesApi$ReadGameLines, must be bigger than or equal to 0.")
      }

      # explore
      for (query_item in `season`) {
        query_params[["season"]] <- c(query_params[["season"]], list(`season` = query_item))
      }

      # explore
      for (query_item in `sessions`) {
        # validate enum values
        if (!is.null(query_item) && !(query_item %in% c("R", "P"))) {
          stop("Invalid value for sessions when calling LinesApi$ReadGameLines. Must be [R, P].")
        }
        query_params[["sessions"]] <- c(query_params[["sessions"]], list(`sessions` = query_item))
      }

      # explore
      for (query_item in `game_id`) {
        query_params[["game_id"]] <- c(query_params[["game_id"]], list(`game_id` = query_item))
      }

      # explore
      for (query_item in `team`) {
        query_params[["team"]] <- c(query_params[["team"]], list(`team` = query_item))
      }

      # explore
      for (query_item in `opp_team`) {
        query_params[["opp_team"]] <- c(query_params[["opp_team"]], list(`opp_team` = query_item))
      }

      # explore
      for (query_item in `strength_state`) {
        # validate enum values
        if (!is.null(query_item) && !(query_item %in% c("5v5", "4v4", "3v3", "5v4", "5v3", "4v3", "4v5", "3v4", "3v5"))) {
          stop("Invalid value for strength_state when calling LinesApi$ReadGameLines. Must be [5v5, 4v4, 3v3, 5v4, 5v3, 4v3, 4v5, 3v4, 3v5].")
        }
        query_params[["strength_state"]] <- c(query_params[["strength_state"]], list(`strength_state` = query_item))
      }

      query_params[["score_state"]] <- `score_state`

      if (!is.null(`level`) && !(`level` %in% c("game", "period"))) {
        stop("Invalid value for level when calling LinesApi$ReadGameLines. Must be [game, period].")
      }
      query_params[["level"]] <- `level`

      query_params[["linemates"]] <- `linemates`

      query_params[["opposition"]] <- `opposition`

      query_params[["limit"]] <- `limit`

      query_params[["offset"]] <- `offset`

      local_var_url_path <- "/api/v1/chicken_nhl/lines/game"
      # OAuth-related settings
      is_oauth <- TRUE
      oauth_scopes <- ""

      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          self$api_client$WriteFile(local_var_resp, data_file)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$DeserializeResponse(local_var_resp, "LinesGameResponse"),
          error = function(e) {
            stop("Failed to deserialize response")
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        return(local_var_resp)
      } 
      
      local_var_error_msg <- local_var_resp$response_as_text()      
      if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(paste("Server returned ", local_var_resp$status_code, " response status code."), local_var_resp)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new("API client error", local_var_resp)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || local_var_resp$response == "") {
          local_var_resp$response <- "API server error"
        }
        return(local_var_resp)
      }
    },

    #' @description
    #' Read Line Ids
    #'
    #' @param season (optional) No description
    #' @param sessions (optional) No description
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #'
    #' @return array[character]
    ReadLineIds = function(season = NULL, sessions = NULL, data_file = NULL, ...) {
      local_var_response <- self$ReadLineIdsWithHttpInfo(season, sessions, data_file = data_file, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        return(local_var_response$content)
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        return(local_var_response)
      }
    },

    #' @description
    #' Read Line Ids
    #'
    #' @param season (optional) No description
    #' @param sessions (optional) No description
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #'
    #' @return API response (array[character]) with additional information such as HTTP status code, headers
    ReadLineIdsWithHttpInfo = function(season = NULL, sessions = NULL, data_file = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE



      # explore
      for (query_item in `season`) {
        query_params[["season"]] <- c(query_params[["season"]], list(`season` = query_item))
      }

      # explore
      for (query_item in `sessions`) {
        # validate enum values
        if (!is.null(query_item) && !(query_item %in% c("R", "P"))) {
          stop("Invalid value for sessions when calling LinesApi$ReadLineIds. Must be [R, P].")
        }
        query_params[["sessions"]] <- c(query_params[["sessions"]], list(`sessions` = query_item))
      }

      local_var_url_path <- "/api/v1/chicken_nhl/lines/line_ids"
      # OAuth-related settings
      is_oauth <- TRUE
      oauth_scopes <- ""

      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          self$api_client$WriteFile(local_var_resp, data_file)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$DeserializeResponse(local_var_resp, "array[character]"),
          error = function(e) {
            stop("Failed to deserialize response")
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        return(local_var_resp)
      } 
      
      local_var_error_msg <- local_var_resp$response_as_text()      
      if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(paste("Server returned ", local_var_resp$status_code, " response status code."), local_var_resp)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new("API client error", local_var_resp)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || local_var_resp$response == "") {
          local_var_resp$response <- "API server error"
        }
        return(local_var_resp)
      }
    },

    #' @description
    #' Read Lines Game Ids
    #'
    #' @param season (optional) No description
    #' @param sessions (optional) No description
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #'
    #' @return array[integer]
    ReadLinesGameIds = function(season = NULL, sessions = NULL, data_file = NULL, ...) {
      local_var_response <- self$ReadLinesGameIdsWithHttpInfo(season, sessions, data_file = data_file, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        return(local_var_response$content)
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        return(local_var_response)
      }
    },

    #' @description
    #' Read Lines Game Ids
    #'
    #' @param season (optional) No description
    #' @param sessions (optional) No description
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #'
    #' @return API response (array[integer]) with additional information such as HTTP status code, headers
    ReadLinesGameIdsWithHttpInfo = function(season = NULL, sessions = NULL, data_file = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE



      # explore
      for (query_item in `season`) {
        query_params[["season"]] <- c(query_params[["season"]], list(`season` = query_item))
      }

      # explore
      for (query_item in `sessions`) {
        # validate enum values
        if (!is.null(query_item) && !(query_item %in% c("R", "P"))) {
          stop("Invalid value for sessions when calling LinesApi$ReadLinesGameIds. Must be [R, P].")
        }
        query_params[["sessions"]] <- c(query_params[["sessions"]], list(`sessions` = query_item))
      }

      local_var_url_path <- "/api/v1/chicken_nhl/lines/game_ids"
      # OAuth-related settings
      is_oauth <- TRUE
      oauth_scopes <- ""

      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          self$api_client$WriteFile(local_var_resp, data_file)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$DeserializeResponse(local_var_resp, "array[integer]"),
          error = function(e) {
            stop("Failed to deserialize response")
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        return(local_var_resp)
      } 
      
      local_var_error_msg <- local_var_resp$response_as_text()      
      if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(paste("Server returned ", local_var_resp$status_code, " response status code."), local_var_resp)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new("API client error", local_var_resp)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || local_var_resp$response == "") {
          local_var_resp$response <- "API server error"
        }
        return(local_var_resp)
      }
    },

    #' @description
    #' Read Season Lines
    #'
    #' @param season (optional) No description
    #' @param sessions (optional) No description
    #' @param team (optional) No description
    #' @param opp_team (optional) No description
    #' @param strength_state (optional) No description
    #' @param score_state (optional) No description
    #' @param linemates (optional) No description
    #' @param opposition (optional) No description
    #' @param limit (optional) No description (default value: 10000)
    #' @param offset (optional) No description (default value: 0)
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #'
    #' @return LinesSeasonResponse
    ReadSeasonLines = function(season = NULL, sessions = NULL, team = NULL, opp_team = NULL, strength_state = NULL, score_state = NULL, linemates = NULL, opposition = NULL, limit = 10000, offset = 0, data_file = NULL, ...) {
      local_var_response <- self$ReadSeasonLinesWithHttpInfo(season, sessions, team, opp_team, strength_state, score_state, linemates, opposition, limit, offset, data_file = data_file, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        return(local_var_response$content)
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        return(local_var_response)
      }
    },

    #' @description
    #' Read Season Lines
    #'
    #' @param season (optional) No description
    #' @param sessions (optional) No description
    #' @param team (optional) No description
    #' @param opp_team (optional) No description
    #' @param strength_state (optional) No description
    #' @param score_state (optional) No description
    #' @param linemates (optional) No description
    #' @param opposition (optional) No description
    #' @param limit (optional) No description (default value: 10000)
    #' @param offset (optional) No description (default value: 0)
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #'
    #' @return API response (LinesSeasonResponse) with additional information such as HTTP status code, headers
    ReadSeasonLinesWithHttpInfo = function(season = NULL, sessions = NULL, team = NULL, opp_team = NULL, strength_state = NULL, score_state = NULL, linemates = NULL, opposition = NULL, limit = 10000, offset = 0, data_file = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE









      if (`limit` > 50000) {
        stop("Invalid value for `limit` when calling LinesApi$ReadSeasonLines, must be smaller than or equal to 50000.")
      }
      if (`limit` < 1) {
        stop("Invalid value for `limit` when calling LinesApi$ReadSeasonLines, must be bigger than or equal to 1.")
      }

      if (`offset` < 0) {
        stop("Invalid value for `offset` when calling LinesApi$ReadSeasonLines, must be bigger than or equal to 0.")
      }

      # explore
      for (query_item in `season`) {
        query_params[["season"]] <- c(query_params[["season"]], list(`season` = query_item))
      }

      # explore
      for (query_item in `sessions`) {
        # validate enum values
        if (!is.null(query_item) && !(query_item %in% c("R", "P"))) {
          stop("Invalid value for sessions when calling LinesApi$ReadSeasonLines. Must be [R, P].")
        }
        query_params[["sessions"]] <- c(query_params[["sessions"]], list(`sessions` = query_item))
      }

      # explore
      for (query_item in `team`) {
        query_params[["team"]] <- c(query_params[["team"]], list(`team` = query_item))
      }

      # explore
      for (query_item in `opp_team`) {
        query_params[["opp_team"]] <- c(query_params[["opp_team"]], list(`opp_team` = query_item))
      }

      # explore
      for (query_item in `strength_state`) {
        # validate enum values
        if (!is.null(query_item) && !(query_item %in% c("5v5", "4v4", "3v3", "5v4", "5v3", "4v3", "4v5", "3v4", "3v5"))) {
          stop("Invalid value for strength_state when calling LinesApi$ReadSeasonLines. Must be [5v5, 4v4, 3v3, 5v4, 5v3, 4v3, 4v5, 3v4, 3v5].")
        }
        query_params[["strength_state"]] <- c(query_params[["strength_state"]], list(`strength_state` = query_item))
      }

      query_params[["score_state"]] <- `score_state`

      query_params[["linemates"]] <- `linemates`

      query_params[["opposition"]] <- `opposition`

      query_params[["limit"]] <- `limit`

      query_params[["offset"]] <- `offset`

      local_var_url_path <- "/api/v1/chicken_nhl/lines/season"
      # OAuth-related settings
      is_oauth <- TRUE
      oauth_scopes <- ""

      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          self$api_client$WriteFile(local_var_resp, data_file)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$DeserializeResponse(local_var_resp, "LinesSeasonResponse"),
          error = function(e) {
            stop("Failed to deserialize response")
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        return(local_var_resp)
      } 
      
      local_var_error_msg <- local_var_resp$response_as_text()      
      if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(paste("Server returned ", local_var_resp$status_code, " response status code."), local_var_resp)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new("API client error", local_var_resp)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || local_var_resp$response == "") {
          local_var_resp$response <- "API server error"
        }
        return(local_var_resp)
      }
    }
  )
)
