#' chickenstats API
#'
#' API for downloading NHL data
#'
#' The version of the OpenAPI document: 0.1.3
#' Contact: chicken@chickenandstats.com
#' Generated by: https://openapi-generator.tech
#'
#' @docType class
#' @title PlayByPlay operations
#' @description PlayByPlayApi
#' @format An \code{R6Class} generator object
#' @field api_client Handles the client-server communication.
#'
#' @examples
#' \dontrun{
#' ####################  ReadPbp  ####################
#'
#' library(chickenstats.api)
#' var_season <- c(123) # array[integer] |  (Optional)
#' var_sessions <- c("R") # array[character] |  (Optional)
#' var_game_id <- c(123) # array[integer] |  (Optional)
#' var_event <- c("inner_example") # array[character] |  (Optional)
#' var_player_1 <- c("inner_example") # array[character] |  (Optional)
#' var_goalie <- c("inner_example") # array[character] |  (Optional)
#' var_event_team <- c("inner_example") # array[character] |  (Optional)
#' var_opp_team <- c("inner_example") # array[character] |  (Optional)
#' var_strength_state <- c("5v5") # array[character] |  (Optional)
#' var_limit <- 10000 # integer |  (Optional)
#' var_offset <- 0 # integer |  (Optional)
#'
#' #Read Pbp
#' api_instance <- PlayByPlayApi$new()
#'
#' # Configure OAuth2 access token for authorization: OAuth2PasswordBearer
#' api_instance$api_client$access_token <- Sys.getenv("ACCESS_TOKEN")
#'
#' # to save the result into a file, simply add the optional `data_file` parameter, e.g.
#' # result <- api_instance$ReadPbp(season = var_season, sessions = var_sessions, game_id = var_game_id, event = var_event, player_1 = var_player_1, goalie = var_goalie, event_team = var_event_team, opp_team = var_opp_team, strength_state = var_strength_state, limit = var_limit, offset = var_offsetdata_file = "result.txt")
#' result <- api_instance$ReadPbp(season = var_season, sessions = var_sessions, game_id = var_game_id, event = var_event, player_1 = var_player_1, goalie = var_goalie, event_team = var_event_team, opp_team = var_opp_team, strength_state = var_strength_state, limit = var_limit, offset = var_offset)
#' dput(result)
#'
#'
#' ####################  ReadPbpGameIds  ####################
#'
#' library(chickenstats.api)
#' var_season <- c(123) # array[integer] |  (Optional)
#' var_sessions <- c("R") # array[character] |  (Optional)
#'
#' #Read Pbp Game Ids
#' api_instance <- PlayByPlayApi$new()
#'
#' # Configure OAuth2 access token for authorization: OAuth2PasswordBearer
#' api_instance$api_client$access_token <- Sys.getenv("ACCESS_TOKEN")
#'
#' # to save the result into a file, simply add the optional `data_file` parameter, e.g.
#' # result <- api_instance$ReadPbpGameIds(season = var_season, sessions = var_sessionsdata_file = "result.txt")
#' result <- api_instance$ReadPbpGameIds(season = var_season, sessions = var_sessions)
#' dput(result)
#'
#'
#' ####################  ReadPbpPlayIds  ####################
#'
#' library(chickenstats.api)
#' var_season <- c(123) # array[integer] |  (Optional)
#' var_sessions <- c("R") # array[character] |  (Optional)
#' var_game_id <- c(123) # array[integer] |  (Optional)
#'
#' #Read Pbp Play Ids
#' api_instance <- PlayByPlayApi$new()
#'
#' # Configure OAuth2 access token for authorization: OAuth2PasswordBearer
#' api_instance$api_client$access_token <- Sys.getenv("ACCESS_TOKEN")
#'
#' # to save the result into a file, simply add the optional `data_file` parameter, e.g.
#' # result <- api_instance$ReadPbpPlayIds(season = var_season, sessions = var_sessions, game_id = var_game_iddata_file = "result.txt")
#' result <- api_instance$ReadPbpPlayIds(season = var_season, sessions = var_sessions, game_id = var_game_id)
#' dput(result)
#'
#'
#' }
#' @importFrom R6 R6Class
#' @importFrom base64enc base64encode
#' @export
PlayByPlayApi <- R6::R6Class(
  "PlayByPlayApi",
  public = list(
    api_client = NULL,

    #' @description
    #' Initialize a new PlayByPlayApi.
    #'
    #' @param api_client An instance of API client.
    initialize = function(api_client) {
      if (!missing(api_client)) {
        self$api_client <- api_client
      } else {
        self$api_client <- ApiClient$new()
      }
    },

    #' @description
    #' Read Pbp
    #'
    #' @param season (optional) No description
    #' @param sessions (optional) No description
    #' @param game_id (optional) No description
    #' @param event (optional) No description
    #' @param player_1 (optional) No description
    #' @param goalie (optional) No description
    #' @param event_team (optional) No description
    #' @param opp_team (optional) No description
    #' @param strength_state (optional) No description
    #' @param limit (optional) No description (default value: 10000)
    #' @param offset (optional) No description (default value: 0)
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #'
    #' @return PbpResponse
    ReadPbp = function(season = NULL, sessions = NULL, game_id = NULL, event = NULL, player_1 = NULL, goalie = NULL, event_team = NULL, opp_team = NULL, strength_state = NULL, limit = 10000, offset = 0, data_file = NULL, ...) {
      local_var_response <- self$ReadPbpWithHttpInfo(season, sessions, game_id, event, player_1, goalie, event_team, opp_team, strength_state, limit, offset, data_file = data_file, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        return(local_var_response$content)
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        return(local_var_response)
      }
    },

    #' @description
    #' Read Pbp
    #'
    #' @param season (optional) No description
    #' @param sessions (optional) No description
    #' @param game_id (optional) No description
    #' @param event (optional) No description
    #' @param player_1 (optional) No description
    #' @param goalie (optional) No description
    #' @param event_team (optional) No description
    #' @param opp_team (optional) No description
    #' @param strength_state (optional) No description
    #' @param limit (optional) No description (default value: 10000)
    #' @param offset (optional) No description (default value: 0)
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #'
    #' @return API response (PbpResponse) with additional information such as HTTP status code, headers
    ReadPbpWithHttpInfo = function(season = NULL, sessions = NULL, game_id = NULL, event = NULL, player_1 = NULL, goalie = NULL, event_team = NULL, opp_team = NULL, strength_state = NULL, limit = 10000, offset = 0, data_file = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE










      if (`limit` > 100000) {
        stop("Invalid value for `limit` when calling PlayByPlayApi$ReadPbp, must be smaller than or equal to 100000.")
      }
      if (`limit` < 1) {
        stop("Invalid value for `limit` when calling PlayByPlayApi$ReadPbp, must be bigger than or equal to 1.")
      }

      if (`offset` < 0) {
        stop("Invalid value for `offset` when calling PlayByPlayApi$ReadPbp, must be bigger than or equal to 0.")
      }

      # explore
      for (query_item in `season`) {
        query_params[["season"]] <- c(query_params[["season"]], list(`season` = query_item))
      }

      # explore
      for (query_item in `sessions`) {
        # validate enum values
        if (!is.null(query_item) && !(query_item %in% c("R", "P"))) {
          stop("Invalid value for sessions when calling PlayByPlayApi$ReadPbp. Must be [R, P].")
        }
        query_params[["sessions"]] <- c(query_params[["sessions"]], list(`sessions` = query_item))
      }

      # explore
      for (query_item in `game_id`) {
        query_params[["game_id"]] <- c(query_params[["game_id"]], list(`game_id` = query_item))
      }

      # explore
      for (query_item in `event`) {
        query_params[["event"]] <- c(query_params[["event"]], list(`event` = query_item))
      }

      # explore
      for (query_item in `player_1`) {
        query_params[["player_1"]] <- c(query_params[["player_1"]], list(`player_1` = query_item))
      }

      # explore
      for (query_item in `goalie`) {
        query_params[["goalie"]] <- c(query_params[["goalie"]], list(`goalie` = query_item))
      }

      # explore
      for (query_item in `event_team`) {
        query_params[["event_team"]] <- c(query_params[["event_team"]], list(`event_team` = query_item))
      }

      # explore
      for (query_item in `opp_team`) {
        query_params[["opp_team"]] <- c(query_params[["opp_team"]], list(`opp_team` = query_item))
      }

      # explore
      for (query_item in `strength_state`) {
        # validate enum values
        if (!is.null(query_item) && !(query_item %in% c("5v5", "4v4", "3v3", "5v4", "5v3", "4v3", "4v5", "3v4", "3v5"))) {
          stop("Invalid value for strength_state when calling PlayByPlayApi$ReadPbp. Must be [5v5, 4v4, 3v3, 5v4, 5v3, 4v3, 4v5, 3v4, 3v5].")
        }
        query_params[["strength_state"]] <- c(query_params[["strength_state"]], list(`strength_state` = query_item))
      }

      query_params[["limit"]] <- `limit`

      query_params[["offset"]] <- `offset`

      local_var_url_path <- "/api/v1/chicken_nhl/play_by_play"
      # OAuth-related settings
      is_oauth <- TRUE
      oauth_scopes <- ""

      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          self$api_client$WriteFile(local_var_resp, data_file)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$DeserializeResponse(local_var_resp, "PbpResponse"),
          error = function(e) {
            stop("Failed to deserialize response")
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        return(local_var_resp)
      } 
      
      local_var_error_msg <- local_var_resp$response_as_text()      
      if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(paste("Server returned ", local_var_resp$status_code, " response status code."), local_var_resp)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new("API client error", local_var_resp)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || local_var_resp$response == "") {
          local_var_resp$response <- "API server error"
        }
        return(local_var_resp)
      }
    },

    #' @description
    #' Read Pbp Game Ids
    #'
    #' @param season (optional) No description
    #' @param sessions (optional) No description
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #'
    #' @return array[integer]
    ReadPbpGameIds = function(season = NULL, sessions = NULL, data_file = NULL, ...) {
      local_var_response <- self$ReadPbpGameIdsWithHttpInfo(season, sessions, data_file = data_file, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        return(local_var_response$content)
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        return(local_var_response)
      }
    },

    #' @description
    #' Read Pbp Game Ids
    #'
    #' @param season (optional) No description
    #' @param sessions (optional) No description
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #'
    #' @return API response (array[integer]) with additional information such as HTTP status code, headers
    ReadPbpGameIdsWithHttpInfo = function(season = NULL, sessions = NULL, data_file = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE



      # explore
      for (query_item in `season`) {
        query_params[["season"]] <- c(query_params[["season"]], list(`season` = query_item))
      }

      # explore
      for (query_item in `sessions`) {
        # validate enum values
        if (!is.null(query_item) && !(query_item %in% c("R", "P"))) {
          stop("Invalid value for sessions when calling PlayByPlayApi$ReadPbpGameIds. Must be [R, P].")
        }
        query_params[["sessions"]] <- c(query_params[["sessions"]], list(`sessions` = query_item))
      }

      local_var_url_path <- "/api/v1/chicken_nhl/play_by_play/game_ids"
      # OAuth-related settings
      is_oauth <- TRUE
      oauth_scopes <- ""

      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          self$api_client$WriteFile(local_var_resp, data_file)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$DeserializeResponse(local_var_resp, "array[integer]"),
          error = function(e) {
            stop("Failed to deserialize response")
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        return(local_var_resp)
      } 
      
      local_var_error_msg <- local_var_resp$response_as_text()      
      if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(paste("Server returned ", local_var_resp$status_code, " response status code."), local_var_resp)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new("API client error", local_var_resp)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || local_var_resp$response == "") {
          local_var_resp$response <- "API server error"
        }
        return(local_var_resp)
      }
    },

    #' @description
    #' Read Pbp Play Ids
    #'
    #' @param season (optional) No description
    #' @param sessions (optional) No description
    #' @param game_id (optional) No description
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #'
    #' @return array[integer]
    ReadPbpPlayIds = function(season = NULL, sessions = NULL, game_id = NULL, data_file = NULL, ...) {
      local_var_response <- self$ReadPbpPlayIdsWithHttpInfo(season, sessions, game_id, data_file = data_file, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        return(local_var_response$content)
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        return(local_var_response)
      }
    },

    #' @description
    #' Read Pbp Play Ids
    #'
    #' @param season (optional) No description
    #' @param sessions (optional) No description
    #' @param game_id (optional) No description
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #'
    #' @return API response (array[integer]) with additional information such as HTTP status code, headers
    ReadPbpPlayIdsWithHttpInfo = function(season = NULL, sessions = NULL, game_id = NULL, data_file = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE




      # explore
      for (query_item in `season`) {
        query_params[["season"]] <- c(query_params[["season"]], list(`season` = query_item))
      }

      # explore
      for (query_item in `sessions`) {
        # validate enum values
        if (!is.null(query_item) && !(query_item %in% c("R", "P"))) {
          stop("Invalid value for sessions when calling PlayByPlayApi$ReadPbpPlayIds. Must be [R, P].")
        }
        query_params[["sessions"]] <- c(query_params[["sessions"]], list(`sessions` = query_item))
      }

      # explore
      for (query_item in `game_id`) {
        query_params[["game_id"]] <- c(query_params[["game_id"]], list(`game_id` = query_item))
      }

      local_var_url_path <- "/api/v1/chicken_nhl/play_by_play/play_ids"
      # OAuth-related settings
      is_oauth <- TRUE
      oauth_scopes <- ""

      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          self$api_client$WriteFile(local_var_resp, data_file)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$DeserializeResponse(local_var_resp, "array[integer]"),
          error = function(e) {
            stop("Failed to deserialize response")
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        return(local_var_resp)
      } 
      
      local_var_error_msg <- local_var_resp$response_as_text()      
      if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(paste("Server returned ", local_var_resp$status_code, " response status code."), local_var_resp)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new("API client error", local_var_resp)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || local_var_resp$response == "") {
          local_var_resp$response <- "API server error"
        }
        return(local_var_resp)
      }
    }
  )
)
