#' chickenstats API
#'
#' API for downloading NHL data
#'
#' The version of the OpenAPI document: 0.1.5
#' Contact: chicken@chickenandstats.com
#' Generated by: https://openapi-generator.tech
#'
#' @docType class
#' @title Players operations
#' @description PlayersApi
#' @format An \code{R6Class} generator object
#' @field api_client Handles the client-server communication.
#'
#' @examples
#' \dontrun{
#' ####################  ReadPlayer  ####################
#'
#' library(chickenstats.api)
#' var_api_id <- 56 # integer | 
#'
#' #Read Player
#' api_instance <- PlayersApi$new()
#'
#' # to save the result into a file, simply add the optional `data_file` parameter, e.g.
#' # result <- api_instance$ReadPlayer(var_api_iddata_file = "result.txt")
#' result <- api_instance$ReadPlayer(var_api_id)
#' dput(result)
#'
#'
#' ####################  ReadPlayers  ####################
#'
#' library(chickenstats.api)
#' var_name <- "name_example" # character |  (Optional)
#' var_position <- "position_example" # character |  (Optional)
#' var_eh_id <- "eh_id_example" # character |  (Optional)
#' var_limit <- 10000 # integer |  (Optional)
#' var_offset <- 0 # integer |  (Optional)
#'
#' #Read Players
#' api_instance <- PlayersApi$new()
#'
#' # to save the result into a file, simply add the optional `data_file` parameter, e.g.
#' # result <- api_instance$ReadPlayers(name = var_name, position = var_position, eh_id = var_eh_id, limit = var_limit, offset = var_offsetdata_file = "result.txt")
#' result <- api_instance$ReadPlayers(name = var_name, position = var_position, eh_id = var_eh_id, limit = var_limit, offset = var_offset)
#' dput(result)
#'
#'
#' }
#' @importFrom R6 R6Class
#' @importFrom base64enc base64encode
#' @export
PlayersApi <- R6::R6Class(
  "PlayersApi",
  public = list(
    api_client = NULL,

    #' @description
    #' Initialize a new PlayersApi.
    #'
    #' @param api_client An instance of API client.
    initialize = function(api_client) {
      if (!missing(api_client)) {
        self$api_client <- api_client
      } else {
        self$api_client <- ApiClient$new()
      }
    },

    #' @description
    #' Read Player
    #'
    #' @param api_id 
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #'
    #' @return PlayerPublic
    ReadPlayer = function(api_id, data_file = NULL, ...) {
      local_var_response <- self$ReadPlayerWithHttpInfo(api_id, data_file = data_file, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        return(local_var_response$content)
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        return(local_var_response)
      }
    },

    #' @description
    #' Read Player
    #'
    #' @param api_id 
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #'
    #' @return API response (PlayerPublic) with additional information such as HTTP status code, headers
    ReadPlayerWithHttpInfo = function(api_id, data_file = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`api_id`)) {
        stop("Missing required parameter `api_id`.")
      }


      local_var_url_path <- "/api/v1/chicken_nhl/players/{api_id}"
      if (!missing(`api_id`)) {
        local_var_url_path <- gsub("\\{api_id\\}", URLencode(as.character(`api_id`), reserved = TRUE), local_var_url_path)
      }


      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          self$api_client$WriteFile(local_var_resp, data_file)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$DeserializeResponse(local_var_resp, "PlayerPublic"),
          error = function(e) {
            stop("Failed to deserialize response")
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        return(local_var_resp)
      } 
      
      local_var_error_msg <- local_var_resp$response_as_text()      
      if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(paste("Server returned ", local_var_resp$status_code, " response status code."), local_var_resp)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new("API client error", local_var_resp)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || local_var_resp$response == "") {
          local_var_resp$response <- "API server error"
        }
        return(local_var_resp)
      }
    },

    #' @description
    #' Read Players
    #'
    #' @param name (optional) No description
    #' @param position (optional) No description
    #' @param eh_id (optional) No description
    #' @param limit (optional) No description (default value: 10000)
    #' @param offset (optional) No description (default value: 0)
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #'
    #' @return PlayerResponse
    ReadPlayers = function(name = NULL, position = NULL, eh_id = NULL, limit = 10000, offset = 0, data_file = NULL, ...) {
      local_var_response <- self$ReadPlayersWithHttpInfo(name, position, eh_id, limit, offset, data_file = data_file, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        return(local_var_response$content)
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        return(local_var_response)
      }
    },

    #' @description
    #' Read Players
    #'
    #' @param name (optional) No description
    #' @param position (optional) No description
    #' @param eh_id (optional) No description
    #' @param limit (optional) No description (default value: 10000)
    #' @param offset (optional) No description (default value: 0)
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #'
    #' @return API response (PlayerResponse) with additional information such as HTTP status code, headers
    ReadPlayersWithHttpInfo = function(name = NULL, position = NULL, eh_id = NULL, limit = 10000, offset = 0, data_file = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE




      if (`limit` > 50000) {
        stop("Invalid value for `limit` when calling PlayersApi$ReadPlayers, must be smaller than or equal to 50000.")
      }
      if (`limit` < 1) {
        stop("Invalid value for `limit` when calling PlayersApi$ReadPlayers, must be bigger than or equal to 1.")
      }

      if (`offset` < 0) {
        stop("Invalid value for `offset` when calling PlayersApi$ReadPlayers, must be bigger than or equal to 0.")
      }

      query_params[["name"]] <- `name`

      query_params[["position"]] <- `position`

      query_params[["eh_id"]] <- `eh_id`

      query_params[["limit"]] <- `limit`

      query_params[["offset"]] <- `offset`

      local_var_url_path <- "/api/v1/chicken_nhl/players"

      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          self$api_client$WriteFile(local_var_resp, data_file)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$DeserializeResponse(local_var_resp, "PlayerResponse"),
          error = function(e) {
            stop("Failed to deserialize response")
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        return(local_var_resp)
      } 
      
      local_var_error_msg <- local_var_resp$response_as_text()      
      if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(paste("Server returned ", local_var_resp$status_code, " response status code."), local_var_resp)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new("API client error", local_var_resp)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || local_var_resp$response == "") {
          local_var_resp$response <- "API server error"
        }
        return(local_var_resp)
      }
    }
  )
)
