#' chickenstats API
#'
#' API for downloading NHL data
#'
#' The version of the OpenAPI document: 0.1.5
#' Contact: chicken@chickenandstats.com
#' Generated by: https://openapi-generator.tech
#'
#' @docType class
#' @title Rosters operations
#' @description RostersApi
#' @format An \code{R6Class} generator object
#' @field api_client Handles the client-server communication.
#'
#' @examples
#' \dontrun{
#' ####################  ReadRosterGameIds  ####################
#'
#' library(chickenstats.api)
#' var_api_id <- c(123) # array[integer] |  (Optional)
#' var_team <- c("inner_example") # array[character] |  (Optional)
#' var_limit <- 10000 # integer |  (Optional)
#' var_offset <- 0 # integer |  (Optional)
#'
#' #Read Roster Game Ids
#' api_instance <- RostersApi$new()
#'
#' # Configure OAuth2 access token for authorization: OAuth2PasswordBearer
#' api_instance$api_client$access_token <- Sys.getenv("ACCESS_TOKEN")
#'
#' # to save the result into a file, simply add the optional `data_file` parameter, e.g.
#' # result <- api_instance$ReadRosterGameIds(api_id = var_api_id, team = var_team, limit = var_limit, offset = var_offsetdata_file = "result.txt")
#' result <- api_instance$ReadRosterGameIds(api_id = var_api_id, team = var_team, limit = var_limit, offset = var_offset)
#' dput(result)
#'
#'
#' ####################  ReadRosters  ####################
#'
#' library(chickenstats.api)
#' var_game_id <- c(123) # array[integer] |  (Optional)
#' var_api_id <- c(123) # array[integer] |  (Optional)
#' var_team <- c("inner_example") # array[character] |  (Optional)
#' var_include <- c("player") # array[character] |  (Optional)
#' var_limit <- 10000 # integer |  (Optional)
#' var_offset <- 0 # integer |  (Optional)
#'
#' #Read Rosters
#' api_instance <- RostersApi$new()
#'
#' # Configure OAuth2 access token for authorization: OAuth2PasswordBearer
#' api_instance$api_client$access_token <- Sys.getenv("ACCESS_TOKEN")
#'
#' # to save the result into a file, simply add the optional `data_file` parameter, e.g.
#' # result <- api_instance$ReadRosters(game_id = var_game_id, api_id = var_api_id, team = var_team, include = var_include, limit = var_limit, offset = var_offsetdata_file = "result.txt")
#' result <- api_instance$ReadRosters(game_id = var_game_id, api_id = var_api_id, team = var_team, include = var_include, limit = var_limit, offset = var_offset)
#' dput(result)
#'
#'
#' }
#' @importFrom R6 R6Class
#' @importFrom base64enc base64encode
#' @export
RostersApi <- R6::R6Class(
  "RostersApi",
  public = list(
    api_client = NULL,

    #' @description
    #' Initialize a new RostersApi.
    #'
    #' @param api_client An instance of API client.
    initialize = function(api_client) {
      if (!missing(api_client)) {
        self$api_client <- api_client
      } else {
        self$api_client <- ApiClient$new()
      }
    },

    #' @description
    #' Read Roster Game Ids
    #'
    #' @param api_id (optional) No description
    #' @param team (optional) No description
    #' @param limit (optional) No description (default value: 10000)
    #' @param offset (optional) No description (default value: 0)
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #'
    #' @return array[integer]
    ReadRosterGameIds = function(api_id = NULL, team = NULL, limit = 10000, offset = 0, data_file = NULL, ...) {
      local_var_response <- self$ReadRosterGameIdsWithHttpInfo(api_id, team, limit, offset, data_file = data_file, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        return(local_var_response$content)
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        return(local_var_response)
      }
    },

    #' @description
    #' Read Roster Game Ids
    #'
    #' @param api_id (optional) No description
    #' @param team (optional) No description
    #' @param limit (optional) No description (default value: 10000)
    #' @param offset (optional) No description (default value: 0)
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #'
    #' @return API response (array[integer]) with additional information such as HTTP status code, headers
    ReadRosterGameIdsWithHttpInfo = function(api_id = NULL, team = NULL, limit = 10000, offset = 0, data_file = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE



      if (`limit` > 50000) {
        stop("Invalid value for `limit` when calling RostersApi$ReadRosterGameIds, must be smaller than or equal to 50000.")
      }
      if (`limit` < 1) {
        stop("Invalid value for `limit` when calling RostersApi$ReadRosterGameIds, must be bigger than or equal to 1.")
      }

      if (`offset` < 0) {
        stop("Invalid value for `offset` when calling RostersApi$ReadRosterGameIds, must be bigger than or equal to 0.")
      }

      # explore
      for (query_item in `api_id`) {
        query_params[["api_id"]] <- c(query_params[["api_id"]], list(`api_id` = query_item))
      }

      # explore
      for (query_item in `team`) {
        query_params[["team"]] <- c(query_params[["team"]], list(`team` = query_item))
      }

      query_params[["limit"]] <- `limit`

      query_params[["offset"]] <- `offset`

      local_var_url_path <- "/api/v1/chicken_nhl/rosters/game_ids"
      # OAuth-related settings
      is_oauth <- TRUE
      oauth_scopes <- ""

      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          self$api_client$WriteFile(local_var_resp, data_file)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$DeserializeResponse(local_var_resp, "array[integer]"),
          error = function(e) {
            stop("Failed to deserialize response")
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        return(local_var_resp)
      } 
      
      local_var_error_msg <- local_var_resp$response_as_text()      
      if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(paste("Server returned ", local_var_resp$status_code, " response status code."), local_var_resp)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new("API client error", local_var_resp)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || local_var_resp$response == "") {
          local_var_resp$response <- "API server error"
        }
        return(local_var_resp)
      }
    },

    #' @description
    #' Read Rosters
    #'
    #' @param game_id (optional) No description
    #' @param api_id (optional) No description
    #' @param team (optional) No description
    #' @param include (optional) No description
    #' @param limit (optional) No description (default value: 10000)
    #' @param offset (optional) No description (default value: 0)
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #'
    #' @return RosterResponse
    ReadRosters = function(game_id = NULL, api_id = NULL, team = NULL, include = NULL, limit = 10000, offset = 0, data_file = NULL, ...) {
      local_var_response <- self$ReadRostersWithHttpInfo(game_id, api_id, team, include, limit, offset, data_file = data_file, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        return(local_var_response$content)
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        return(local_var_response)
      }
    },

    #' @description
    #' Read Rosters
    #'
    #' @param game_id (optional) No description
    #' @param api_id (optional) No description
    #' @param team (optional) No description
    #' @param include (optional) No description
    #' @param limit (optional) No description (default value: 10000)
    #' @param offset (optional) No description (default value: 0)
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #'
    #' @return API response (RosterResponse) with additional information such as HTTP status code, headers
    ReadRostersWithHttpInfo = function(game_id = NULL, api_id = NULL, team = NULL, include = NULL, limit = 10000, offset = 0, data_file = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE





      if (`limit` > 50000) {
        stop("Invalid value for `limit` when calling RostersApi$ReadRosters, must be smaller than or equal to 50000.")
      }
      if (`limit` < 1) {
        stop("Invalid value for `limit` when calling RostersApi$ReadRosters, must be bigger than or equal to 1.")
      }

      if (`offset` < 0) {
        stop("Invalid value for `offset` when calling RostersApi$ReadRosters, must be bigger than or equal to 0.")
      }

      # explore
      for (query_item in `game_id`) {
        query_params[["game_id"]] <- c(query_params[["game_id"]], list(`game_id` = query_item))
      }

      # explore
      for (query_item in `api_id`) {
        query_params[["api_id"]] <- c(query_params[["api_id"]], list(`api_id` = query_item))
      }

      # explore
      for (query_item in `team`) {
        query_params[["team"]] <- c(query_params[["team"]], list(`team` = query_item))
      }

      # explore
      for (query_item in `include`) {
        # validate enum values
        if (!is.null(query_item) && !(query_item %in% c("player", "game"))) {
          stop("Invalid value for include when calling RostersApi$ReadRosters. Must be [player, game].")
        }
        query_params[["include"]] <- c(query_params[["include"]], list(`include` = query_item))
      }

      query_params[["limit"]] <- `limit`

      query_params[["offset"]] <- `offset`

      local_var_url_path <- "/api/v1/chicken_nhl/rosters"
      # OAuth-related settings
      is_oauth <- TRUE
      oauth_scopes <- ""

      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          self$api_client$WriteFile(local_var_resp, data_file)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$DeserializeResponse(local_var_resp, "RosterResponse"),
          error = function(e) {
            stop("Failed to deserialize response")
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        return(local_var_resp)
      } 
      
      local_var_error_msg <- local_var_resp$response_as_text()      
      if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(paste("Server returned ", local_var_resp$status_code, " response status code."), local_var_resp)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new("API client error", local_var_resp)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || local_var_resp$response == "") {
          local_var_resp$response <- "API server error"
        }
        return(local_var_resp)
      }
    }
  )
)
